### ISSUE TITLE
How to verify that Cobee is found?

### ISSUE THREAD

**Issue by ggravlingen** [marthoc/hassio-addons#1]
Hi,

This might be one layer of inception too many, but I'm running a hass.io docker in a Ubuntu virtual machine on my PC. I'm able to install the plugin into hass.io and to access the API. In the API, however, I'm not able to add any devices, nor use the reset devices feature. The latter works if I'm using the API directly from my PC. I have a feeling that the Conbee is not initialized properly. Got any advice on how to verify that?

Thanks,
Patrik

**Comment by marthoc** [comment]
Could be a lot of things going on, let's start at the ground floor. 

Is the Conbee hardware being passed-through properly from your VM host to the VM? Check this by installing the SSH add-on in Hass.io and ssh'ing in, then do `hassio host hardware`. A list of detected hardware should be returned and one of the entries under "serial" should be /dev/ttyUSB0, like so:
```
{
    "result": "ok",
    "data": {
        "serial": [
            "/dev/ttyS0",
            "/dev/ttyS3",
            "/dev/ttyS2",
            "/dev/ttyUSB0",
            "/dev/ttyS1"
        ],
...
```
If /dev/ttyUSB0 _doesn't_ show up, then there's a problem with your VM not having access to the Conbee hardware.

**Comment by ggravlingen** [comment]
Thanks for your advise! Doesn't look to good when running that command:
```
core-ssh:~# hassio host hardware
{
    "result": "ok",
    "data": {
        "serial": [
            "/dev/ttyS18",
            "/dev/ttyS29",
            "/dev/ttyS6",
            "/dev/ttyS7",
            "/dev/ttyS15",
            "/dev/ttyS19",
            "/dev/ttyS17",
            "/dev/ttyS11",
            "/dev/ttyS27",
            "/dev/ttyS24",
            "/dev/ttyS26",
            "/dev/ttyUSB0",
            "/dev/ttyS31",
            "/dev/ttyS20",
            "/dev/ttyS28",
            "/dev/ttyS9",
            "/dev/ttyS13",
            "/dev/ttyS2",
            "/dev/ttyS14",
            "/dev/ttyS10",
            "/dev/ttyS16",
            "/dev/ttyS8",
            "/dev/ttyS22",
            "/dev/ttyS12",
            "/dev/ttyS30",
            "/dev/ttyS5",
            "/dev/ttyS4",
            "/dev/ttyS3",
            "/dev/ttyS0",
            "/dev/ttyS23",
            "/dev/ttyS1",
            "/dev/ttyS21",
            "/dev/ttyS25"
        ],
        "input": [
            "VirtualBox mouse integration",
            "Power Button",
            "Sleep Button",
            "VirtualBox USB Tablet",
            "Video Bus",
            "ImExPS/2 Generic Explorer Mouse",
            "AT Translated Set 2 keyboard"
        ],
        "disk": [
            "/dev/sda",
            "/dev/sda5",
            "/dev/sda2",
            "/dev/sda1"
        ],
        "gpio": [],
        "audio": {
            "0": {
                "name": "ICH - Intel 82801AA-ICH",
                "type": "I82801AAICH",
                "devices": {
                    "0": "digital audio capture",
                    "1": "digital audio capture"
                }
            }
        }
    }
}
```

Running dmesg in the VM indicates the Conbee has been initialized. I'll look into forwarding it into the docker image during the weekend and revert in this issue.

**Comment by marthoc** [comment]
It does look like the Hass.io supervisor is seeing the Conbee: /dev/ttyUSB0.

One thing you can try as a test is to just run the base Docker image (not the Hass.io addon) and see if the Conbee initializes:

`docker run -it --net=host --device=/dev/ttyUSB0 marthoc/deconz`

That will run the base image (that the Hass.io addon is based on) in interactive mode so that you can watch the output.

**Comment by ggravlingen** [comment]
Got it to work now! It probably worked all along, but I musunderstood the web GUI. Couldn't get anything to show up in there. Checking directly against the API listed the sensors though.

Thanks for your help!
