### ISSUE TITLE
VNC config doesnt save

### ISSUE THREAD

**Issue by Tobbe82** [marthoc/hassio-addons#101]
Trying to start the VNC on my Pi running addon deCONZ 2.2 on hassio 0.91.4

in the config box I add:

{
  "device": "/dev/ttyUSB0",
  "vnc": {
   "active": true,
   "port": 5900,
   "password": "changeme"
  }
}

hitting save, but it reverts back to only:
{
  "device": "/dev/ttyUSB0",
}
Am I doing something wrong?

**Comment by alistairg** [comment]
I just spent a while staring at this same issue. I bet you've installed the "community" version of deCONZ, vs Marthoc's. Make sure you follow the instructions to add his repository, then install his version vs the community one...

**Comment by marthoc** [comment]
Yes this is almost certainly the issue. Follow the instructions in this repo.
