### ISSUE TITLE
Database doesn't save / persist?

### ISSUE THREAD

**Issue by alistairg** [marthoc/hassio-addons#103]
I can configure my network via the webui or the cool VNC remote service... but when I restart my Hass instance all my names are gone from the VNC view, and everything but my group names is gone from the web ui.

Something somewhere doesn't get persisted properly - any ideas?

**Comment by marthoc** [comment]
This should not be happening, are you still experiencing this issue?

**Comment by pergolafabio** [comment]
yes, i see this issue too, not happened in past before .65 

i save them in phoscon, in vnc i see the name changing, after restart container, in VNC all names are back to original, but in phoscon  its still the real configured name
