### ISSUE TITLE
Xiaomi sensors losing connection

### ISSUE THREAD

**Issue by Sholofly** [marthoc/hassio-addons#104]
Hi there,

I'm running this addon  on HassOs 2.12 with home assistant up-to-date (0.93). in combination with:

dresden elektronik
ConBee II
Version 2.05.63 / 3-4-2019
Firmware 26420700

 All running on an intel I5 laptop running ProxMox VE 5.4-3 with hassosova image.
I only have two Xiaomi aqara windows/door sensors version 20161128.
After installing the addon I am able to pair both sensors but they are losing connection after one hour or so.

The addon logs:

```
[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.63
[Hass.io] Web UI port: 8080
[Hass.io] Websockets port: 8443
[Hass.io] deCONZ device: /dev/ttyACM0
[Hass.io] Starting in minimal mode, without VNC GUI
libpng warning: iCCP: known incorrect sRGB profile
14:39:17:880 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/
14:39:17:977 CTRL. 3.16.214:39:18:073 COM: /dev/ttyACM0 / serialno: 
14:39:18:073 COM: --dev: /dev/ttyACM0 (ConBee II)
14:39:18:082 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
14:39:18:492 parent process /bin/sh
14:39:18:492 gw run mode: docker/hassio
14:39:18:493 GW sd-card image version file does not exist: /data/.local/share/dresden-elektronik/deCONZ/gw-version
14:39:18:519 DB sqlite version 3.16.2
14:39:18:521 DB PRAGMA page_count: 30
14:39:18:522 DB PRAGMA page_size: 4096
14:39:18:522 DB PRAGMA freelist_count: 0
14:39:18:522 DB file size 122880 bytes, free pages 0
14:39:18:522 DB PRAGMA user_version: 6
14:39:18:522 DB cleanup
14:39:18:540 DB create temporary views
14:39:18:591 don't close database yet, keep open for 900 seconds
14:39:18:591 started websocket server at port 8443
14:39:18:621 discovery updated announce interval to 10 minutes
14:39:18:716 GW firmware update not supported on x86 linux headless
14:39:18:717 found node plugin: libde_rest_plugin.so - REST API Plugin
14:39:18:734 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
14:39:18:742 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
14:39:18:756 COM: /dev/ttyACM0 / serialno: 
14:39:18:756 COM: --dev: /dev/ttyACM0 (ConBee II)
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
14:39:19:105 Device firmware version 0x26420700
14:39:19:109 unlocked max nodes: 200
14:39:19:213 Device protocol version: 0x0108
14:39:19:223 new node - ext: 0x00212effff0409ea, nwk: 0x0000
14:39:19:369 SensorNode 4 set node 0x00158d0002bfc3bd
14:39:19:479 SensorNode 3 set node 0x00158d0002c7b90d
14:39:19:687 Current channel 11
14:39:19:708 CTRL ANT_CTRL 0x03
14:39:19:741 Device protocol version: 0x0108
14:39:19:807 Current channel 11
14:39:19:828 CTRL ANT_CTRL 0x03
14:39:23:923 Announced to internet
14:39:26:192 New websocket 192.168.178.168:55424 (state: 3) 
14:39:28:442 scan skip host .180
```
Can anyone tell me how I can fix or at least debug this issue?

**Comment by krihil** [comment]
I`m actually having the same issue with my setup. ConBee II with three Xiaomi Aqara door/window sensors. The sensors pair properly at first but looses connection in a hour or so.

There are several similar issues reported on the deConz repository as well and I hope this commit would fix the issue:
https://github.com/dresden-elektronik/deconz-rest-plugin/commit/31ef3962a4507e6310c23e4c497278f1fedb050b

If it does then we just need to wait for the add-on to update as well.

**Comment by Sholofly** [comment]
> I`m actually having the same issue with my setup. ConBee II with three Xiaomi Aqara door/window sensors. The sensors pair properly at first but looses connection in a hour or so.
> 
> There are several similar issues reported on the deConz repository as well and I hope this commit would fix the issue:
> [dresden-elektronik/deconz-rest-plugin@31ef396](https://github.com/dresden-elektronik/deconz-rest-plugin/commit/31ef3962a4507e6310c23e4c497278f1fedb050b)
> 
> If it does then we just need to wait for the add-on to update as well.

Thanks for the link. Missed that one. Let's wait en see :)

**Comment by hgelpke** [comment]
I'm in the same boat. My sensors seem to work fine if it's just the coordinator but adding a router into the mix messes them up.

**Comment by pergolafabio** [comment]
seems .65 release is out, fixes connection to xiaomi sensors

**Comment by marthoc** [comment]
Even though there's no confirmation that .65 fixes this problem, since this is not strictly related to this Add-on, I'm going to close this issue.
