### ISSUE TITLE
Missing Path / No Alexa discovery

### ISSUE THREAD

**Issue by DabbbelDei** [marthoc/hassio-addons#108]
Hello everyone,

i am going nuts.. my Alexa won't find my Phoscon GW. So i saw the issue #759. The Problem was solved with changing "dresden elektronik" to "Royal Philips Electronics" in the /usr/share/deCONZ/webapp/description_in.xml file.
BUT on my Raspberry under /usr/share is NO deCONZ folder. Not at Hassio configurator nor SSH or SMB.

i don't know what to do.. 

Thanks for the help

**Comment by marthoc** [comment]
You should be able to find the deCONZ data directory by ssh'ing into your Hass.io system and navigating to /data/.local/share/dresden-elektronik/deCONZ.

**Comment by DabbbelDei** [comment]
![grafik](https://user-images.githubusercontent.com/51137097/59555305-8337d080-8fb0-11e9-9c19-7fe8955fbee3.png)
