### ISSUE TITLE
Can't find new entities

### ISSUE THREAD

**Issue by isabellaalstrom** [marthoc/hassio-addons#11]
I have the addon installed with my hass.io running on ubuntu on an intel nuc in docker. The addon finds my conbee but the conbee can't find anything I try to add. I tried putting the conbee in my windows computer and downloading deconz there, and then it finds everything. Also tried making a backup on the windows verison and loading that into the addon, it shows the entities but don't react to state changes.

**Comment by Nicxe** [comment]
I have the same problem on my rPi 3b, Deconz are connect to by Conbee but I can't add any lights

**Comment by isabellaalstrom** [comment]
Fix for my issue was adding a longer usb cable between nuc and conbee. Apparently some distubance of the signal was going on.
