### ISSUE TITLE
Bump to 2.05.65

### ISSUE THREAD

**Issue by pergolafabio** [marthoc/hassio-addons#110]
Hi @marthoc 
seems the long awaited .65 is out, can you update this for us Home Assistant Addon users?

thnx a lot!

**Comment by corvy** [comment]
+1 😎

tir. 4. jun. 2019, 16:00 skrev pergolafabio <notifications@github.com>:

**Comment by hgelpke** [comment]
That would be much appreciated.

**Comment by marthoc** [comment]
Bumped!
