### ISSUE TITLE
deconz firmware update issues

### ISSUE THREAD

**Issue by haakonstorm** [marthoc/hassio-addons#111]
Latest HA on hassio on RP3B+, raspbee 
Firmware update available:

hassio addon log contain:
"GW sd-card image version file does not exist"

and then:
core-ssh:~# hassio addons logs 69bb46cb_deconz|grep -i firm
19:08:18:449 0xD0CF5EFFFE290C29 error APSDE-DATA.confirm: 0xA7 on task
19:08:33:700 0x000B57FFFE30676F error APSDE-DATA.confirm: 0xA7 on task
19:08:45:501 0x90FD9FFFFE8CFDA3 error APSDE-DATA.confirm: 0xA7 on task
19:09:03:232 0x000B57FFFEBAC88F error APSDE-DATA.confirm: 0xA7 on task
19:09:09:981 GW firmware version: 0x26320500
19:09:09:981 GW firmware version shall be updated to: 0x26330500
19:09:20:973 0xD0CF5EFFFE290C29 error APSDE-DATA.confirm: 0xA7 on task
19:09:36:344 0x000B57FFFE30676F error APSDE-DATA.confirm: 0xA7 on task
19:09:48:175 0x90FD9FFFFE8CFDA3 error APSDE-DATA.confirm: 0xA7 on task
19:10:05:416 0x000B57FFFEBAC88F error APSDE-DATA.confirm: 0xA7 on task
19:10:22:437 0xD0CF5EFFFE290C29 error APSDE-DATA.confirm: 0xA7 on task

How to update firmware / find the filename?

**Comment by marthoc** [comment]
Looks like this is the updated firmware version: 0x26330500. When you run the script it will give you a couple of files to choose from, select that one.
