### ISSUE TITLE
Can no longer add TRÅDFRI remote control

### ISSUE THREAD

**Issue by Arkoxs** [marthoc/hassio-addons#13]
Am I the only one or do more people have issues in adding the TRÅDFRI remote controls?

Just installed this version:
Version 2.05.31 / 22-6-2018
Firmware 261F0500

Devices/Switches, add New Switch, IKEA, select the TRÅDFRI remote control.
Then press the sync button 4x within 5 seconds. Red led flashes 6x.
Nothing happens until "Failed to connect"

**Comment by jantje88** [comment]
Yes, got the exact same issue with the [Tradfri remote](https://www.ikea.com/nl/nl/catalog/products/30338849/).

Using a Raspbee on a RPi3.

**Comment by marthoc** [comment]
I don't think this issue is specific to the add-on, closing.
