### ISSUE TITLE
Raspbee module not detected on new HassOS image

### ISSUE THREAD

**Issue by rafuz** [marthoc/hassio-addons#17]
On the new images version of hassio based on HassOS the config.txt seems not to work the same.
I have added the following lines to it:

```
enable_uart=1
dtoverlay=pi3-disable-bt
```

Even adding a blank line in the end I can't get bluetooth disabled and UART enabled for Raspbee.

**Comment by tikkerei** [comment]
Also I tried to add :
```
enable_uart=1
dtoverlay=pi3-disable-bt
```
But it didn’t work, I have removed this two lines and leaved only one mentioned below.

**SOLUTION**:
Just add the line to the end of config.txt
```
dtoverlay=pi3-miniuart-bt
```

**Comment by rafuz** [comment]
I have managed to migrate to a pi 3 b+ with HassOS and Deconz Addon using Raspbee.
I can confirm that everything works using the correct config line. 
Anyway I find that on HassOS all my zigbee tap devices react really slow... everything seems to take between 3-5 seconds to give feedback if it acts at all.
I will try to understand where it takes time to elaborate as a switch in my house works this way:

`Physical Switch ---> Raspbee ---> Deconz ----> Home Assistant ---> Node-Red ---> Home Assistant`

This flow usually takes less than 0.5 seconds on my ResinOS implementation. Everything is installed on the same pi with HassIO

**Comment by marthoc** [comment]
Updated README.md with these instructions. Thanks!
