### ISSUE TITLE
Debugging pairing issues?

### ISSUE THREAD

**Issue by repvik** [marthoc/hassio-addons#18]
I've got a couple of Xiaomi wireless buttons that Deconz apparently supports. I can pair them as "other" sensors using pwa interface, and the connection wizard completes. But it does not show up in pwa (which doesn't matter that much, since not all devices show up), but it doesn't show up in hassio either. 

It appears to pair correctly, so how do I figure out what goes wrong?

**Comment by repvik** [comment]
Using the POST api I can see that it has been paired correctly:

`{
  "config": {
    "battery": null,
    "on": true,
    "reachable": true,
    "temperature": 0
  },
  "ep": 1,
  "etag": "c98644d28f70aef61a3c3121389645dd",
  "manufacturername": "LUMI",
  "mode": 1,
  "modelid": "lumi.sensor_switch",
  "name": "lumi.sensor_switch",
  "state": {
    "buttonevent": 1002,
    "lastupdated": "2018-07-29T21:43:54"
  },
  "type": "ZHASwitch",
  "uniqueid": "00:15:8d:00:01:87:0e:15-01-0006"
}`

But it does not show up in hass, even after several restarts.

**Comment by rafuz** [comment]
These devices will never show in hass as an entity.
You can "catch" the operation of these switches in hass filterning deconz.event class in the message bus.
I use zigbee switches (not xiaomi) in all my home and I can easily operate anything with them.
