### ISSUE TITLE
aqara water leak sensor conbee

### ISSUE THREAD

**Issue by lastessa** [marthoc/hassio-addons#22]
When i try to add water leak sensor to hassio via marthoc addon (pwa web GUI)
sensor does not add and shown in pwa and ha. But addon log show next log:

00:01:37:512 GW firmware version: 0x26240500
00:01:37:512 GW firmware version is up to date: 0x26240500
00:01:37:724 Announced to internet
00:01:37:724 discovery server date: Sun, 30 Sep 2018 21:01:37 GMT
00:01:37:724 local time seems to be ok
00:01:37:725 discovery found version 2.04.35 for update channel stable
00:01:43:580 New websocket 192.168.1.40:59442 (state: 3)
00:01:45:210 New websocket 192.168.1.56:53574 (state: 3)
00:02:00:819 send permit join, duration: 59
00:02:00:850 scan skip host .56
00:02:10:525 scan finished
00:02:10:817 device announce 0x00158D0002332E68 (0x683B) mac capabilities 0x80
00:02:10:817 set fast probe address to 0x00158D0002332E68 (0x683B)
00:02:10:817 device announce 0x00158D0002332E68 (0x683B) mac capabilities 0x80
00:02:10:817 set fast probe address to 0x00158D0002332E68 (0x683B)
00:02:10:818 0x10DC nwk changed to 0x683B
00:02:10:865 ZCL attribute report 0x00158D0002332E68 for cluster 0x0000, ep 0x01
00:02:10:866 0x00158D0002332E68 skip Xiaomi attribute 0x0005
00:02:11:665 ZCL attribute report 0x00158D0002332E68 for cluster 0x0000, ep 0x01
00:02:11:665 0x00158D0002332E68 extract Xiaomi special
00:02:11:665 01 battery 3015 (0x0BC7)
00:02:11:665 03 temperature 30 °C
00:02:11:665 04 unknown 424 (0x01A8)
00:02:11:665 05 RSSI dB (?) 115 (0x0073)
00:02:11:665 06 LQI (?) 4294967296 (0x0100000000)
00:02:11:665 08 unknown 516 (0x0204)
00:02:11:665 0a unknown 0 (0x0000)
00:02:11:665 64 on/off 0
00:02:11:818 [2] get active endpoints for 0x00158d0002332e68
00:02:12:491 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:15:568 DB save zll database items 0x00000800
00:02:15:593 DB saved in 25 ms
00:02:15:593 don’t close database yet, keep open for 900 seconds
00:02:15:626 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:18:910 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:22:127 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:25:346 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:28:563 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:31:782 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:32:352 Current channel 11
00:02:32:384 Device TTL 3001 s
00:02:34:000 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:38:217 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:41:453 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:44:670 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:47:890 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:51:107 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:54:325 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:57:560 [3.1] get IAS Zone type for 0x00158d0002332e68
00:02:59:819 send permit join, duration: 59
00:03:00:778 [3.1] get IAS Zone type for 0x00158d0002332e68
00:03:03:996 [3.1] get IAS Zone type for 0x00158d0002332e68
00:03:07:215 [3.1] get IAS Zone type for 0x00158d0002332e68
00:03:10:434 [3.1] get IAS Zone type for 0x00158d0002332e68
00:03:13:668 [3.1] get IAS Zone type for 0x00158d0002332e68
00:03:16:887 [3.1] get IAS Zone type for 0x00158d0002332e68
00:03:32:157 device announce 0x00158D000233761B (0x3CA1) mac capabilities 0x80
00:03:32:157 set fast probe address to 0x00158D000233761B (0x3CA1)
00:03:32:157 device announce 0x00158D000233761B (0x3CA1) mac capabilities 0x80
00:03:32:157 set fast probe address to 0x00158D000233761B (0x3CA1)
00:03:32:157 0x0000 nwk changed to 0x3CA1
00:03:32:188 ZCL attribute report 0x00158D000233761B for cluster 0x0000, ep 0x01
00:03:32:188 0x00158D000233761B skip Xiaomi attribute 0x0005
00:03:32:364 Current channel 11
00:03:32:396 Device TTL 2941 s
00:03:32:990 ZCL attribute report 0x00158D000233761B for cluster 0x0000, ep 0x01
00:03:32:990 0x00158D000233761B extract Xiaomi special
00:03:32:990 01 battery 3015 (0x0BC7)
00:03:32:990 03 temperature 25 °C
00:03:32:990 04 unknown 424 (0x01A8)
00:03:32:990 05 RSSI dB (?) 69 (0x0045)
00:03:32:990 06 LQI (?) 4294967296 (0x0100000000)
00:03:32:990 08 unknown 516 (0x0204)
00:03:32:990 0a unknown 0 (0x0000)
00:03:32:990 64 on/off 0
00:03:33:207 [2] get active endpoints for 0x00158d000233761b
00:03:33:815 [3.1] get IAS Zone type for 0x00158d000233761b
00:03:36:933 [3.1] get IAS Zone type for 0x00158d000233761b
00:03:37:319 DB save zll database items 0x00000800
00:03:37:341 DB saved in 22 ms
00:03:37:341 don’t close database yet, keep open for 900 seconds
00:03:40:184 [3.1] get IAS Zone type for 0x00158d000233761b
00:03:40:899 ZCL attribute report 0x00158D000233761B for cluster 0x0000, ep 0x01
00:03:40:899 0x00158D000233761B skip Xiaomi attribute 0x0005
00:03:40:899 0x00158D000233761B extract Xiaomi special
00:03:40:899 01 battery 3015 (0x0BC7)
00:03:40:899 03 temperature 25 °C
00:03:40:899 04 unknown 424 (0x01A8)
00:03:40:899 05 RSSI dB (?) 69 (0x0045)
00:03:40:899 06 LQI (?) 131072 (0x0000020000)
00:03:40:899 08 unknown 516 (0x0204)
00:03:40:899 0a unknown 0 (0x0000)
00:03:40:899 64 on/off 0
00:03:41:337 [3.1] get IAS Zone type for 0x00158d000233761b
00:03:44:572 [3.1] get IAS Zone type for 0x00158d000233761b
00:03:46:819 send permit join, duration: 0
00:03:52:819 send permit join, duration: 59
00:04:21:057 device announce 0x00158D000233761B (0x9A4B) mac capabilities 0x80
00:04:21:057 set fast probe address to 0x00158D000233761B (0x9A4B)
00:04:21:057 device announce 0x00158D000233761B (0x9A4B) mac capabilities 0x80

So it show some info when i press button on sensor.
Any suggestion about this issue?

deconz: conbee
hassio: 0.79.1
marthoc addon: 2.05.39
sensor: aqara water leak sensor

**Comment by marthoc** [comment]
This sounds like a deCONZ issue, not specific to this Add-on. You should raise an issue here: https://github.com/dresden-elektronik/deconz-rest-plugin.
