### ISSUE TITLE
After upgrading to 2.05.42 firmware update fails

### ISSUE THREAD

**Issue by ted1979** [marthoc/hassio-addons#28]
Hi,

I just upgraded deCONZ to 2.05.42 and now the firmware upgrade fails with the following message:

Enter C for Conbee, R for RaspBee, or press Enter now to exit: C

Listing attached devices...

rmmod: ERROR: Module ftdi_sio is in use
rmmod: ERROR: Module usbserial is in use by: ftdi_sio
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10
RaspBee: /dev/ttyAMA0 (default)

   1  FTDI device found

failed to open FTDI device (0) status = 3

**Comment by marthoc** [comment]
Did you stop the deCONZ addon? And possibly remove other USB devices from the system? This error should only appear if the Conbee is in use.

**Comment by marthoc** [comment]
Must have been some quirk with the driver still holding its connection to the Conbee open. Glad to hear it’s resolved.
