### ISSUE TITLE
Settings on Phoscon app

### ISSUE THREAD

**Issue by GaryGoethals** [marthoc/hassio-addons#29]
Hi,
I've installed the add on and can access the Phoscon login.
I can scan for lights but there's nothing found.
If I go in hassio, integrations, deCONZ zigbee gateway and want to configure,
I receive the message "go to deCONZ system setting" but I can't seem to find it.
Am I doing something wrong?
thanks for the help and the app!

**Comment by nomadzx** [comment]
@GaryGoethals, I've had a similar issue. I think an update either of Hassio or deConz has changed something. Previously, I think discovery automatically found the Raspbee gateway for configuration, but now it doesn't.

But from what you are saying, just in case I have misunderstood, you might need to go to http://hassio.local:8080 and you will see the Phoscan software and where you search for lights.

**Comment by marthoc** [comment]
@GaryGoethals - what’s your setup? RaspBee or Conbee? What platform?

**Comment by GaryGoethals** [comment]
Hi,
Thanks for the reply.
I have hassio running on a raspberry pi and a Conbee stick attached to it.

Gary
