### ISSUE TITLE
Upgrading IKEA Trådfri OTA?

### ISSUE THREAD

**Issue by repvik** [marthoc/hassio-addons#30]
deCONZ can upgrade IKEA Trådfri units OTA. I can't find a way to do this with this plugin however. Is there something I'm missing? Could this feature be added?

**Comment by marthoc** [comment]
I believe that this feature requires access to the deconz GUI and they haven’t made this accessible over the web interface yet. I’ve looked into adding access to the GUI in the past but I’ll take another look soon and update this issue.

**Comment by fiskfan** [comment]
@manup, how do you execute this if you run this as a addon in Hass.io? 
Im a noob, and i cannot find how to access the otau folder to put the firmware files or run the script from/to...

**Comment by marthoc** [comment]
@fiskfan You can't. I need to add this to the base image somehow before it will work, and I'm not sure how I'm going to achieve that yet.

**Comment by cogneato** [comment]
@marthoc I don't use this, but I've run into another user trying to update their Trådfri through deconz. Could you make use of the /share directory and have users put it there?

**Comment by Shaolo** [comment]
Have there been any advances on this? Perhaps integration of the script from here: [deCONZ Ikea OTA download script](https://github.com/dresden-elektronik/deconz-rest-plugin/blob/master/ikea-ota-download.py)

Maybe just run it every 6-24 hours?

**Comment by RedUlf** [comment]
I am also looking for this

**Comment by corvy** [comment]
I have made some progress from the Hass.IO host OS. I can share my findings but basically I just went to the shared storage folder for the docker container, created a /OTAU folder and I find it from the VNC desktop like this. Have not successfully upgraded any nodes yet though....

<img width="1285" alt="screenshot 2019-01-31 at 14 57 46" src="https://user-images.githubusercontent.com/138292/52058885-af563600-2568-11e9-9b54-27e414615f68.png">


My way of doing this was that I ran the python download script on my linux PC, copied the files over to a USB pin drive that I connected to the raspberry running Hass.IO. I enabled SSH to the Host OS using this guide: https://developers.home-assistant.io/docs/en/hassio_debugging.html

When I got SSH access, I enter the host OS by issuing "login" command. 

To list the docker images running issue command:

`docker ps`

Find the "marthoc/hassio-addon-deconz-armhf" one and copy the CONTAINER ID string. Run the following command to find the folder where the persistent data volume is:

`docker inspect -f '{{ .Mounts }}' 123123123123`

Replace the number at the end with container id.  You will get a folder print somewhere locally like: 
/mnt/data/supervisor/addons/data/69bb46cb_deconz/ or something similar. Go to this folder. Create a new folder called "otau", and another called "usb". Mount the usb and copy the files from usb to otau. 

Tip, to find the USB device name do a "dmesg". So then ... please share if anyone have success updating their devices!

**Comment by lb1974** [comment]
Followed corvy's procedure and after restarting the addon I could manually update the firmware and some got updated automatically (I think).

**Comment by lb1974** [comment]
Sorry if this is not the right place. Perhaps it may help. Anyway I altered corvy's procedure a bit. A python3 script to download the files (ssh port 22). then copied the files to the right folder (ssh 22222). Have a look here https://community.home-assistant.io/t/deconz-for-hass-io/41165/357?u=poppe

**Comment by corvy** [comment]
Hello, I cannot get this script to run on HASS.io as it has no python3 bin installed. I think that was why I elected to go the USB way to get them in.

**Comment by RedUlf** [comment]
True. I have the same problem

**Comment by lb1974** [comment]
I have not installed python3, perhaps some addon installed it? I have have no clue. I could only do when I used port 22 not port 22222.
