### ISSUE TITLE
HASS.io and pi offline after browsing through Phoscon app

### ISSUE THREAD

**Issue by jantje88** [marthoc/hassio-addons#31]
When clicking through the Phoscon app for a minute HASS.io and the complete Pi goes offline. Samba share unavailable, no ping response, etc. Only thing that helps is reconnecting the power on the Pi. Does anyone recognize this issue?

Using HASS.io 0.80.3 and Deconz 2.05.39

**Comment by marthoc** [comment]
I’m just throwing out guesses because this is a very strange issue - SD card failing and insufficient power supply are the two possibilities that come to my mind for the Pi completely locking up and requiring a reboot.

**Comment by jantje88** [comment]
I am using an official 2.5A power supply so I guess it should be a failing SD card.
The last few weeks the Pi gets unavailable out of the blue a few times but I not able to trigger this myself besides clicking through the Phoscon app. Quite strange.

Will migrate to a NUC to get a more reliable system.
