### ISSUE TITLE
No deCONZ bridges discovered

### ISSUE THREAD

**Issue by Thoit** [marthoc/hassio-addons#33]
Hi,

Last week I bought a Conbee USB stick. I’ve already installed the deCONZ add-on successfully, and configured /dev/ttyUSB0 as device. 

Unfortunately, it is impossible to connect the Conbee USB stick with Home Assistant. When I try to add the gateway through integrations, the following error appears: No deCONZ bridges discovered. Offcourse I clicked on the authenticate App in the gateway settings. 

What I already did:

-	Upgraded firmware to latest version from October 28. I did an upgrade with my Windows 10 laptop, and also through the add-on 
-	Upgraded Home assistant to latest version (0.81.2)
-	Reinstalled the Add-on
-	Enabled discovery:
-	Added Deconz: Host <IP address>
        o	Also: 127.0.0.1 as IP address
-	Disconnected other USB devices
-	Multiple reboots
-	I Can add my devices in the Phoscon site, but the problem is I cannot use them in HA, because the integration is not working.

When I tried to put the Conbee USB stick into my Windows 10 laptop, Home Assistant detected the Gateway. 

My setup:
-	RPI 2 Model B+
-	HA Version 0.81.2 with HASSIO
-	Conbee USB stick
-	Multiple Xiaomi Aqara doorsensors
-	Aqara Cube
-	Aqara motion sensors

Log from ADD-on:

10:10:05:579 COM: --dev: /dev/ttyUSB0
10:10:05:653 dev /dev/ttyAMA0
10:10:05:653 COM: /dev/ttyUSB0 / serialno: 
10:10:05:729 Device firmware version 0x261F0500
10:10:05:752 unlocked max nodes: 200
10:10:06:041 Device protocol version: 0x0106
This plugin does not support propagateSizeHints()
10:10:06:232 Current channel 11
10:10:06:296 CTRL ANT_CTRL 0x02
10:10:06:408 Device protocol version: 0x0106
10:10:06:600 Current channel 11
10:10:06:664 CTRL ANT_CTRL 0x02
10:10:18:635 Current channel 11
10:10:19:768 Announced to internet
10:10:19:769 discovery server date: Thu, 01 Nov 2018 09:10:19 GMT
10:10:19:769 	 local time seems to be ok
10:11:08:648 dev /dev/ttyAMA0
10:11:08:648 GW firmware version: 0x261f0500
10:11:08:648 GW firmware version shall be updated to: 0x262d0500
10:11:18:636 Current channel 11
10:12:18:635 Current channel 11
10:12:43:624 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state
10:12:43:624 device state timeout ignored in state 5
10:12:43:667 GW firmware start update (device not connected)
10:12:44:145 GW firmware update exit code 1

**Comment by marthoc** [comment]
When integrating with HA you will need to unlock the deconz gateway to allow HA to get an API key. You do this in the Phoscon GUI by selecting Gateway, Advanced, and then Authenticate App. Then go to HA and do the integration and it should successfully retrieve an API key and set up the integration.

**Comment by Thoit** [comment]
> When integrating with HA you will need to unlock the deconz gateway to allow HA to get an API key. You do this in the Phoscon GUI by selecting Gateway, Advanced, and then Authenticate App. Then go to HA and do the integration and it should successfully retrieve an API key and set up the integration.

That's what I mention in the following line: _clicked on the authenticate App in the gateway settings._

**Comment by marthoc** [comment]
I appreciate that, but the error suggests that you may have been doing things out of order. I’d suggest that @Kane610 needs to weigh in on the issue as it sounds like HA is not succcessfully obtaining the key.

**Comment by Kane610** [comment]
Some people seem to have been getting different kind of network issues over the last couple of releases.

Does it work if you manually configure it in configuration.yaml?

deconz:
  host: 127.0.0.1
  port: 80

If you've gotten a api key in another way you can optionally specify it as well
deconz:
  host: 127.0.0.1
  port: 80
  api_key: x

**Comment by epeome5** [comment]
I've actually got the same problem. I connected conbee to the rpi3, checked which name it got (`ttyUSB0`) and the installed the add-on. I added the namn (`/dev/ttyUSB0`) and started the add-on. I could connect to the webUI and connect the first lightbulb. Then i tried add decons by going to configuration --> integration and clicking deconz. At first I forgot to Authenticate App, so it didn't work. Then I Authenticate App in the deconz webUI and tried to add it again by going to going to configuration --> integration and clicking deconz but it still didn't work.

As far as I understand that should be the correct order to do it in?

Now I have tried to add

```
deconz:
  host: 127.0.0.1
  port: 8080
```

to configuration.yaml and that worked like a charm!

Another question:
I added the conbee with the name `/dev/ttyUSB0`, would it be possible to add it with `/dev/serial/by-id/XYZ` instead to prevent the dongel to get another name during a restart since that can make it stop working?

**Comment by marthoc** [comment]
@epeome5 Try using the /dev/serial/by-id/XYZ and let us know if it works!

**Comment by Thoit** [comment]
> Some people seem to have been getting different kind of network issues over the last couple of releases.
> 
> Does it work if you manually configure it in configuration.yaml?
> 
> deconz:
> host: 127.0.0.1
> port: 80
> 
> If you've gotten a api key in another way you can optionally specify it as well
> deconz:
> host: 127.0.0.1
> port: 80
> api_key: x

I've added port: 80 to the configuration, but same problem. In the log in shows: _Error getting deCONZ data from http://127.0.0.1:80/api._

How can I obtain manually a API key?

**Comment by Kane610** [comment]
I've created a fallback in case the discovery fails so it will be possible to manually input host and port in the frontend.

https://github.com/home-assistant/home-assistant/pull/18116

**Comment by epeome5** [comment]
> @epeome5 Try using the /dev/serial/by-id/XYZ and let us know if it works!

Smart! 

I've did that but it didn't seem to work.

In the deconz configuration I added 

```
{
  "deconz_device": "/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_XXXXXXXX-if00",
  "web_port": 8080,
  "websockets_port": 8443,
  "debug_info": 1,
  "debug_aps": 0,
  "debug_zcl": 0,
  "debug_zdp": 0,
  "debug_otau": 0
}
```
Where XXXXXXXX is som letters and numbers.

When logged in to the webUI again my lamps and groups that I've added before in deconz disappeared.

The log says 

```
10:00:51:065 COM: --dev: /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01BK7F-if00
10:00:51:370 dev /dev/ttyAMA0
```

So it seems like it doesn't work. :(

**Comment by Thoit** [comment]
> > @epeome5 Try using the /dev/serial/by-id/XYZ and let us know if it works!
> 
> Smart!
> 
> I've did that but it didn't seem to work.
> 
> In the deconz configuration I added
> 
> ```
> {
>   "deconz_device": "/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_XXXXXXXX-if00",
>   "web_port": 8080,
>   "websockets_port": 8443,
>   "debug_info": 1,
>   "debug_aps": 0,
>   "debug_zcl": 0,
>   "debug_zdp": 0,
>   "debug_otau": 0
> }
> ```
> Where XXXXXXXX is som letters and numbers.
> 
> When logged in to the webUI again my lamps and groups that I've added before in deconz disappeared.
> 
> The log says
> 
> ```
> 10:00:51:065 COM: --dev: /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01BK7F-if00
> 10:00:51:370 dev /dev/ttyAMA0
> ```
> So it seems like it doesn't work. :(

Did you also restart the ADD-on? I've seen a couple of times that the wrong mapping was displayed. After restart of the ADD-on the correct path was shown.

**Comment by epeome5** [comment]
> > > @epeome5 Try using the /dev/serial/by-id/XYZ and let us know if it works!
> > 
> > 
> > Smart!
> > I've did that but it didn't seem to work.
> > In the deconz configuration I added
> > ```
> > {
> >   "deconz_device": "/dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_XXXXXXXX-if00",
> >   "web_port": 8080,
> >   "websockets_port": 8443,
> >   "debug_info": 1,
> >   "debug_aps": 0,
> >   "debug_zcl": 0,
> >   "debug_zdp": 0,
> >   "debug_otau": 0
> > }
> > ```
> > Where XXXXXXXX is som letters and numbers.
> > When logged in to the webUI again my lamps and groups that I've added before in deconz disappeared.
> > The log says
> > ```
> > 10:00:51:065 COM: --dev: /dev/serial/by-id/usb-FTDI_FT230X_Basic_UART_DM01BK7F-if00
> > 10:00:51:370 dev /dev/ttyAMA0
> > ```
> > So it seems like it doesn't work. :(
> 
> Did you also restart the ADD-on? I've seen a couple of times that the wrong mapping was displayed. After restart of the ADD-on the correct path was shown.

Hello,

Yes, i turned of the add-on and changed the info, then turned it on again. I even restarted hassio altogether.

**Comment by marthoc** [comment]
Seems like specifying /dev/serial doesn't work - too bad! This issue is otherwise solved though.
