### ISSUE TITLE
Enable SSL/Encryption

### ISSUE THREAD

**Issue by Maaacus** [marthoc/hassio-addons#35]
Hi! 

I'm quite new to Home Assistant and HASSIO. However I just installed your Deconz addon and got it working seperatly. However I can't connect it to HA yet. I'm wondering if it could be due to my HA is using SSL encryption trough DuckDNS addon. Is there any way to turn of SSL encryption in this addon?

Best regards,

**Comment by marthoc** [comment]
It won’t have anything to do with SSL on your HA instance. Apparently there is some issue with deconz that will be solved in the next HA release. Can you post more about your error?

**Comment by TorulfDanielsson** [comment]
@Maaacus 
I had the same problem. Discovery do not work in this case. Read this: [https://github.com/marthoc/hassio-addons/issues/33#issuecomment-435227793]

Add the code (change host ip to your own) below in configuration.yaml 

`deconz:
  host: 127.0.0.1
  port: 8080`

**Comment by marthoc** [comment]
This should be solved in the latest HA release.
