### ISSUE TITLE
Firmware update does not check for latest FW?

### ISSUE THREAD

**Issue by repvik** [marthoc/hassio-addons#36]
I just updated the firmware on my raspbee, and now the log states the following:
```
14:27:44:776 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262d0500.bin.GCF
14:27:44:776 GW firmware version: 0x262d0500
14:27:44:776 GW firmware version is up to date: 0x262d0500
```

Yet, the latest firmware available is 0x262e0500, from https://www.dresden-elektronik.de/rpi/deconz-firmware/deCONZ_Rpi_0x262e0500.bin.GCF

Why is this firmware not picked up? Is there a way to flash it manually?

**Comment by marthoc** [comment]
This has everything to do with deCONZ and nothing to do with this Add-on: the log messages you are seeing are what is output by deCONZ. I suggest logging a bug on the Dresden Elektronik GitHub repo.
