### ISSUE TITLE
Firmware update never works

### ISSUE THREAD

**Issue by danielsjf** [marthoc/hassio-addons#39]
Ever since I have the Conbee (since August), it seems that I can't do any firmware updates using the deconz addon.

After I click update, I see no connection. When it comes back, it has the same version as before. I also see the following messages in my log.

19:38:01:290 dev /dev/ttyAMA0 
19:38:01:290 GW firmware version: 0x260b0500 19:38:01:290 GW firmware version shall be updated to: 0x262f0500 
19:38:45:311 Current channel 20 
19:39:45:321 Current channel 20 
19:40:11:289 dev /dev/ttyAMA0 
19:40:11:289 GW firmware version: 0x260b0500 19:40:11:289 GW firmware version shall be updated to: 0x262f0500 
19:40:45:315 Current channel 20 
19:41:45:310 Current channel 20 
19:42:21:289 dev /dev/ttyAMA0

After updating, I see the following:

20:06:53:512 New websocket 192.168.1.2:44384 (state: 3) 
20:06:56:917 Websocket disconnected 192.168.1.2:44384 (state: 0) 
20:06:58:214 New websocket 192.168.1.2:44386 (state: 3) 
20:07:06:314 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state 20:07:06:314 device state timeout ignored in state 5 
20:07:06:346 GW firmware start update (device not connected) This plugin does not support propagateSizeHints() 
20:07:07:062 GW firmware update exit code 1 20:07:07:253 Wait reconnect after firmware update 
20:07:08:254 Wait reconnect after firmware update 
20:07:09:253 Wait reconnect after firmware update 
20:07:10:252 Wait reconnect after firmware update 
20:07:11:253 Wait ....
20:07:43:980 Websocket disconnected 192.168.1.2:44386 (state: 0) 
20:07:44:253 Wait reconnect after firmware update 
20:07:45:253 Wait...
20:08:23:250 Wait reconnect after firmware update 
20:08:24:259 COM: --dev: /dev/ttyUSB0 20:08:24:303 dev /dev/ttyAMA0 
20:08:24:303 COM: /dev/ttyUSB0 / serialno:

But the version remains the same.

**Comment by tikkerei** [comment]
Please go to: [https://github.com/marthoc/hassio-addons/blob/master/deconz/FIRMWARE-UPGRADE.md](https://github.com/marthoc/hassio-addons/blob/master/deconz/FIRMWARE-UPGRADE.md)
Just follow the instructions.



> Ever since I have the Conbee (since August), it seems that I can't do any firmware updates using the deconz addon.
> 
> After I click update, I see no connection. When it comes back, it has the same version as before. I also see the following messages in my log.
> 
> 19:38:01:290 dev /dev/ttyAMA0
> 19:38:01:290 GW firmware version: 0x260b0500 19:38:01:290 GW firmware version shall be updated to: 0x262f0500
> 19:38:45:311 Current channel 20
> 19:39:45:321 Current channel 20
> 19:40:11:289 dev /dev/ttyAMA0
> 19:40:11:289 GW firmware version: 0x260b0500 19:40:11:289 GW firmware version shall be updated to: 0x262f0500
> 19:40:45:315 Current channel 20
> 19:41:45:310 Current channel 20
> 19:42:21:289 dev /dev/ttyAMA0
> 
> After updating, I see the following:
> 
> 20:06:53:512 New websocket 192.168.1.2:44384 (state: 3)
> 20:06:56:917 Websocket disconnected 192.168.1.2:44384 (state: 0)
> 20:06:58:214 New websocket 192.168.1.2:44386 (state: 3)
> 20:07:06:314 void zmMaster::handleStateIdle(zmMaster::MasterEvent) not connected goto OFF state 20:07:06:314 device state timeout ignored in state 5
> 20:07:06:346 GW firmware start update (device not connected) This plugin does not support propagateSizeHints()
> 20:07:07:062 GW firmware update exit code 1 20:07:07:253 Wait reconnect after firmware update
> 20:07:08:254 Wait reconnect after firmware update
> 20:07:09:253 Wait reconnect after firmware update
> 20:07:10:252 Wait reconnect after firmware update
> 20:07:11:253 Wait ....
> 20:07:43:980 Websocket disconnected 192.168.1.2:44386 (state: 0)
> 20:07:44:253 Wait reconnect after firmware update
> 20:07:45:253 Wait...
> 20:08:23:250 Wait reconnect after firmware update
> 20:08:24:259 COM: --dev: /dev/ttyUSB0 20:08:24:303 dev /dev/ttyAMA0
> 20:08:24:303 COM: /dev/ttyUSB0 / serialno:
> 
> But the version remains the same.

**Comment by danielsjf** [comment]
@tikkerei Thanks, I followed the procedure there. It finds a FTDI device, but then fails to provide a device number. It fails with status 4. I could find other issues with status 3, but none with status 4.

Actually, deCONZ has been working fine until the last update of the addon. Since then, it lost my full list of devices. The photocon software still works and I can check the gateway from there. The two problems might be related.

For reference, find the log below

![image](https://user-images.githubusercontent.com/6696142/49181967-37e20b80-f359-11e8-8e67-bdfddc443039.png)

**Comment by danielsjf** [comment]
@tikkerei after a reboot everything worked as expected. After the reboot, all my devices are still gone though. They are still in the Phoscon app, but all greyed out. I tried to plug it in my PC and I can still connect to those devices using the stick, so that is not the issue.

**Comment by danielsjf** [comment]
I had to manually reconnect all my devices and remove a few, but they are back now. I'll close the issue since it was clearly not related to the initial issue.
