### ISSUE TITLE
Firmware upgrade

### ISSUE THREAD

**Issue by flick116** [marthoc/hassio-addons#4]
Hi, how do I upgrade the Raspbee Premium firmware while using the addon?

**Comment by marthoc** [comment]
Good question. I’ve not gotten around to making a write up for it yet but it should work with the instructions from the base image. You’ll need to ssh into the base ResinOS, however, there’s no way to avoid that at the moment. So set up SSH into the host ResinOS by following these instructions: https://www.home-assistant.io/developers/hassio/debugging/. 

Then follow the firmware update instructions on this page: https://github.com/marthoc/docker-deconz.

Let me know if you hit any errors and we can debug.

**Comment by flick116** [comment]
Hi,

Thanks for the reply.  I did try that, assuming that it would be the same process.

docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL -v /dev:/dev -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz
docker: Error response from daemon: invalid character 'c' looking for beginning of value.

Any ideas?

Thanks

**Comment by flick116** [comment]
I checked running docker logs and can see that a firmware update is available:

13:55:47:701 dev /dev/ttyAMA0
13:55:47:703 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x261f0500.bin.GCF
13:55:47:704 GW firmware version: 0x26050500
13:55:47:704 GW firmware version shall be updated to: 0x261f0500

But when I run the docker run command as above I get the invalid character error.

**Comment by marthoc** [comment]
Yes now that you mention it another user had posted on a previous issue on the base repo about this. 

Can you try running it like this?
```
docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL --device=/dev/ttyAMA0 -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz
```

**Comment by flick116** [comment]
That's looking a lot better :) It's now flashing the firmware.  Thank you for the speedy response.

**Comment by marthoc** [comment]
No problem. Please let me know if it completes successfully. Please leave this issue open to remind me to add instructions to the README, I’ll close it when that’s done.

**Comment by flick116** [comment]
Yep, it all worked without issue.  Thanks again.

**Comment by alexvandervegt** [comment]
When i try to update the firmware in hassio i get:

-bash: docker: command not found

Any work around for hassio?

**Comment by flick116** [comment]
Did you follow https://www.home-assistant.io/developers/hassio/debugging/?

**Comment by alexvandervegt** [comment]
Thanks, did not know that!

**Comment by alexvandervegt** [comment]
Now i get:

Firmware File: deCONZ_Rpi_0x261f0500.bin.GCF

Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

rmmod: ERROR: Module ftdi_sio is in use
rmmod: ERROR: Module usbserial is in use by: ftdi_sio
GCFFlasher V2_11 (c) dresden elektronik ingenieurtechnik gmbh 2017/12/10

**Comment by marthoc** [comment]
You’re need to remove your other USB device while flashing the Conbee - the flasher needs to unload the kernel modules and can’t while another USB serial device is connected. Annoying I know but you don’t have to do it very often.

**Comment by alexvandervegt** [comment]
I have my power to my Pi through USB...

**Comment by repvik** [comment]
The instructions above don't work with HassOS unfortunately. Is there a way to upgrade firmware when running on HassOS?
From what I can see from skimming the HassOS description, there's no way to run docker commands and not really any way to interact that way with addons from the CLI.

**Comment by jantje88** [comment]
I am also wondering how to upgrade the raspbee premium firmware when using HassOS. Got the error ''docker' is not a hassio command. See 'hassio --help'.' when entering 'docker run -it --rm --device=/dev/ttyAMA0 --privileged --cap-add=ALL -v /lib/modules:/lib/modules --entrypoint "/firmware-update.sh" marthoc/hassio-addon-deconz-armhf' which worked on another Resin installation.

**Comment by bobkarreman** [comment]
@jantje88 You first have to go out of the Hass.io CLI by calling `login`

I took the following steps to update the firmware of my device:

1. Enable SSH following this doc: https://www.home-assistant.io/developers/hassio/debugging/.
    Except for this bug: https://github.com/home-assistant/developers.home-assistant/issues/72
2. Remove any other USB devices
3. Stop the deCONZ hassio Addon from the UI
4. SSH into the host ResinOS `ssh -p 22222 hassio.local
5. In the Hass.io CLI call `login` to go to access the host shell
6. Call the following docker command to start the firmware-update:
`docker run -it --rm --entrypoint "/firmware-update.sh" --privileged --cap-add=ALL --device=/dev/ttyAMA0 -v /lib/modules:/lib/modules -v /sys:/sys marthoc/deconz`


 @marthoc: The only thing I didn't know was which firmware to pick because it showed me 2 with no information what so ever to see which version was the newest. I checked out the file date by accessing the docker container and calling an ls on the firmware folder but I guess there should be a better way?

**Comment by jantje88** [comment]
@bobkarreman Thanks for your tutorial :-)
Unfortunately I get 'n error on the last step (unless the deCONZ add-on is stopped in the Hass.io GUI:  [https://i.imgur.com/tW2Pit9.png](url)

**Comment by bobkarreman** [comment]
@jantje88 You can confirm its stopped by running docker ps and check if the deCONZ container is no longer running. Maybe that helps

**Comment by jantje88** [comment]
@bobkarreman Fixed it. The raspbee was not recognized. See the edit in my previous post. Thanks anyway!

**Comment by RudolfRendier** [comment]
Since V2_05_39 contains another firmware update this thread's information is very relevant. I think these steps should be documented in the readme/wiki, including the proper config-directives for ResinOS en HassOS for both RPi 3B and 3B+.
(Since officialy these operating systems are not supported by DeCONZ)

**Comment by marthoc** [comment]
Firmware upgrade instructions have been added to the README.

**Comment by maxandersen** [comment]
@marthoc  which readme is the info in ? README on this repo seem to not have any info?

**Comment by maxandersen** [comment]
excellent- thanks!

**Comment by maffee** [comment]
Hi,

I'm having trouble upgrading the firmware. Or to be exact, I'm stuck on the part where I need to run the Docker command. When I ssh to the HA, it goes fine. When I try to run Docker commands, it says the command is not found. 

@bobkarreman mentioned that one should issue 'login' command. I'm able to do that, but what username & password is expected here? I think I've tried every combo I can think of. 

I think I also managed to play through the whole Google while trying to figure this out :(

**Comment by bobkarreman** [comment]
@maffee Yes ssh into the hostOS (the os that is running the different docker containers) is different then the ssh access you already have to the HA installation. The host os is available on port 22222 if enabled.

**Comment by maffee** [comment]
New question regarding firmware upgrades for Conbee:

I'm missing something, maybe someone is able to clarify things :)

1. Hass.io addon page for deConz shows an update available. The instructions say that the update fails silently. So my first question is: Do I click the update button at any point? Or after the upgrade script has been run through SSH?



2. Hass.io addon page for deConz shows an update available. Logs from the addon page say:

`16:37:43:942 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262f0500.bin.GCF
16:37:43:942 GW firmware version: 0x262f0500
16:37:43:942 GW firmware version is up to date: 0x262f0500`

How am I to interpret this 'is up to date' part? Run the upgrade script or not?

If I run it, I get this:

`Firmware available for flashing:`

`deCONZ_Rpi_0x261f0500.bin.GCF`
`deCONZ_Rpi_0x262e0500.bin.GCF`
`deCONZ_Rpi_0x262f0500.bin.GCF`

How do I know which is the correct one? What are the differences between those anyway? Some is newer than another? Some is for Conbee, some is for Raspbee? Or does the filename change at all with new versions?

I'm 99% sure I've had the same 3 options for months now.



3. In the Firmware upgrade instructions ([here](https://github.com/marthoc/hassio-addons/blob/master/deconz/FIRMWARE-UPGRADE.md)) there is this part in Step 2:

![image](https://user-images.githubusercontent.com/16758032/53250450-15932c00-36c3-11e9-898c-20bb3f41e2f3.png)

Am I missing something or is the actual command part missing from the instructions? Only the output for the command is shown after that line?

Thanks!

**Comment by marthoc** [comment]
`16:37:43:942 GW firmware version is up to date: 0x262f0500`
Interpret it in the literal way: your firmware is up to date and does not need to be updated.

**Comment by maffee** [comment]
Okay, I think I figured out my mistake. 

> Firmware upgrades from the web UI will fail silently.

This means from the Phoscon UI.

So updating the actual addon from hassio UI works fine. If I'm correct then finally this makes some sense to me :) 

Any chance to get some additional info on this:

> What are the differences between those anyway? Some is newer than another? Some is for Conbee, some is for Raspbee? Or does the filename change at all with new versions?

**Comment by antro31** [comment]
Hi all, I am trying today to run the above script to update my raspbee, but I have the following error message that prevents it to be upgraded:

`/usr/bin/GCFFlasher_internal.bin: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by /usr/lib/libwiringPi.so)`

Any idea on how to solve this?

**Comment by hmrc87** [comment]
I used @antro31 command but with deCONZ_Rpi_0x26330500.bin.GCF I get an error:

(RPi4)
`Device: /dev/ttyAMA0

Firmware File: deCONZ_Rpi_0x26330500.bin.GCF

Are the above device and firmware values correct?
Enter Y to proceed, any other entry to exit: Y

Flashing...

GCFFlasher V3_05 (c) dresden elektronik ingenieurtechnik gmbh
Reboot device /dev/ttyAMA0 (RaspBee)
deCONZ firmware version 26050500
action: reset device RaspBee
action: update firmware after 2 ms
could not sync with bootloader

Flashing Error! Please re-run this script...`
