### ISSUE TITLE
Setup in Apple Safari does not work

### ISSUE THREAD

**Issue by leoMehlig** [marthoc/hassio-addons#40]
After a lot of booting and changing the config on my pi, I noticed, that the problem was my browser. In safari I always got a `Please wait until the search for gateways has finished`. After trying chrome everything worked fine. 
Should I create a PR to mention this in in the README?

**Comment by marthoc** [comment]
This isn't an add-on specific problem, it's related to deCONZ itself. I would open an issue on dresden-elektronik's repo for the deconz-rest-plugin.
