### ISSUE TITLE
deCONZ addon not working

### ISSUE THREAD

**Issue by greencharlie100** [marthoc/hassio-addons#42]
I cannot get any devices (sensors or switches) connected to the Phoscon APP?

I also want to do a firmware update of my Raspbee but I cant as the information required for the update is not available in the logs? 

Firmware update instructions:
https://github.com/marthoc/hassio-addons/blob/master/deconz/FIRMWARE-UPGRADE.md 

Please help!

deCONZ logs:

[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.47
[Hass.io] Web UI port: 8080
[Hass.io] Websockets port: 8443
[Hass.io] deCONZ device: /dev/ttyAMA0
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()

**Comment by greencharlie100** [comment]
I have made some progress. My problem this past few days, is trying to add Xiaomi wireless switch (WXKG03LM) to deCONZ. It does not seem to connect or pass any information?

**Comment by greencharlie100** [comment]
Here are the deCONZ logs when trying to add the wireless switch: 
Log
[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.47
[Hass.io] Web UI port: 8080
[Hass.io] Websockets port: 8443
[Hass.io] deCONZ device: /dev/ttyS0
libpng warning: iCCP: known incorrect sRGB profile
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
This plugin does not support propagateSizeHints()
16:17:47:998 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/
16:17:48:061 CTRL. 3.16.216:17:48:120 COM: --dev: /dev/ttyS0
16:17:48:158 dev /dev/ttyAMA0
16:17:48:158 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
16:17:48:345 parent process /bin/sh
16:17:48:345 gw run mode: normal
16:17:48:345 sd-card cid: 744a60555344202010ffffffff0123e7
16:17:48:346 DB sqlite version 3.16.2
16:17:48:348 DB PRAGMA page_count: 30
16:17:48:348 DB PRAGMA page_size: 4096
16:17:48:348 DB PRAGMA freelist_count: 0
16:17:48:348 DB file size 122880 bytes, free pages 0
16:17:48:348 DB PRAGMA user_version: 6
16:17:48:348 DB cleanup
16:17:48:349 DB create temporary views
16:17:48:355 don't close database yet, keep open for 900 seconds
16:17:48:356 don't close database yet, keep open for 900 seconds
16:17:48:357 started websocket server at port 8443
16:17:48:362 discovery updated announce interval to 10 minutes
16:17:48:366 found node plugin: libde_rest_plugin.so - REST API Plugin
16:17:48:370 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
16:17:48:388 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
16:17:48:388 COM: --dev: /dev/ttyS0
16:17:48:424 dev /dev/ttyAMA0
16:17:48:545 Device firmware version 0x26050500
16:17:48:559 unlocked max nodes: 200
16:17:48:562 New websocket 192.168.1.14:61968 (state: 3) 
16:17:48:739 Device protocol version: 0x0103
16:17:48:757 new node - ext: 0x00212effff024835, nwk: 0x0000
16:17:48:763 Node: id: 1, 00:21:2e:ff:ff:02:48:35 (0x00212EFFFF024835) scene: -110.000000, 115.000000
16:17:48:766 Node: id: 2, 00:15:8d:00:02:81:08:c0 (0x00158D00028108C0) scene: -112.000000, 49.000000
16:17:48:787 Node: id: 4, 00:15:8d:00:02:7c:3e:0e (0x00158D00027C3E0E) scene: 127.000000, 67.000000
16:17:48:803 DB save zll database items 0x00000884
16:17:48:885 DB saved in 82 ms
16:17:48:998 DB save zll database items 0x00000800
16:17:49:301 DB saved in 303 ms
16:17:50:073 DB save zll database items 0x00000800
16:17:50:128 DB saved in 55 ms
16:17:50:348 CTRL [00:21:2e:ff:ff:02:48:35] found reference in zll.db
16:17:50:350 CTRL [00:15:8d:00:02:9b:1a:4c] found reference in zll.db
16:17:50:356 CTRL [00:15:8d:00:02:a1:8a:76] found reference in zll.db
16:17:50:361 DB save zll database items 0x00000800
16:17:50:425 DB saved in 63 ms
16:17:50:472 don't close database yet, keep open for 900 seconds
16:17:50:676 Current channel 15
16:17:50:717 CTRL ANT_CTRL 0x03
16:17:50:794 Device protocol version: 0x0103
16:17:50:924 Current channel 15
16:17:50:964 CTRL ANT_CTRL 0x03
16:17:51:127 DB save zll database items 0x00000800
16:17:51:208 DB saved in 81 ms
16:17:53:161 dev /dev/ttyAMA0
16:17:53:162 GW update firmware found: /usr/share/deCONZ/firmware/deCONZ_Rpi_0x262f0500.bin.GCF
16:17:53:162 GW firmware version: 0x26050500
16:17:53:162 GW firmware version shall be updated to: 0x262f0500
16:17:53:493 Announced to internet
16:17:53:493 discovery server date: Mon, 03 Dec 2018 16:17:53 GMT
16:17:53:494 	 local time seems to be ok
16:17:53:494 discovery found version 2.04.35 for update channel stable
16:17:54:057 CTRL restore cached node 0x00158d0002a18a76
16:17:54:057 Node zombie state changed 0x00158d0002a18a76
16:17:54:058 new node - ext: 0x00158d0002a18a76, nwk: 0x47AF
16:17:54:537 CTRL restore cached node 0x00158d00029b1a4c
16:17:54:537 Node zombie state changed 0x00158d00029b1a4c
16:17:54:539 new node - ext: 0x00158d00029b1a4c, nwk: 0x64A2
16:17:54:539 DB save zll database items 0x00000800
16:17:54:597 DB saved in 57 ms
16:18:00:404 New websocket 127.0.0.1:36104 (state: 3) 
16:18:16:071 scan skip host .8
16:18:28:390 scan finished
16:18:47:929 Current channel 15
16:18:58:744 Websocket disconnected 192.168.1.14:61968 (state: 0) 
16:19:00:349 New websocket 192.168.1.14:62075 (state: 3) 
16:19:06:385 send permit join, duration: 59
16:19:06:625 ZCL attribute report 0x00158D00027C3E0E for cluster 0x0012, ep 0x01
16:19:08:626 ZCL attribute report 0x00158D00027C3E0E for cluster 0x0000, ep 0x01
16:19:18:933 device announce 0x00158D00027C3E0E (0xBA67) mac capabilities 0x80

**Comment by marthoc** [comment]
It looks like all is detected properly on your installation. As to why this device isn’t working, I would suspect a deconz issue (is the device supported?) and suggest opening an issue on the dresden elektronik GitHub page.
