### ISSUE TITLE
https?

### ISSUE THREAD

**Issue by DSorlov** [marthoc/hassio-addons#44]
I'm running Hass.io and loads of other Add-ons over https, this also means that https is then required to load Add-ons. 

From JavaScript when trying to load http url in HomeAssistant:
"Mixed Content: The page at 'https://xxx:8123/deconz' was loaded over HTTPS, but requested an insecure resource 'http://xxx:8080/'. This request has been blocked; the content must be served over HTTPS."

Afaik I have seen there is no https support in Phoscon which means that a small nginx reverse proxy could be implemented to alleviate this: https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/

**Comment by marthoc** [comment]
Does this mean that you're using an iframe?

**Comment by DSorlov** [comment]
Yes; when embedding in the left menu of Home Assistant there is no way to open it without having it in a iFrame afaik. This means that we cannot "integrate" the solution fully.

**Comment by DSorlov** [comment]
*Bump* Most other add-ons offer the possibility to configure SSL for the add-on using ssl-directives.

**Comment by marthoc** [comment]
Yes but isn't this usually when the underlying software itself offers the ability to load its page over https? AFAIK you can only access the deCONZ web interface over http. I don't intend to add a reverse proxy to this add-on just to load the page over https.
