### ISSUE TITLE
Cannot run firmware upgrade script even though protection mode is off

### ISSUE THREAD

**Issue by circuuz** [marthoc/hassio-addons#45]
I cannot run firmware upgrade script. I get a warning about protection mode is enabled and an instruction to disable it.
This even though protection mode is disabled for the addon as you can see in the image below.
I have tried restarting both the addon and HA.

![image](https://user-images.githubusercontent.com/640695/49683488-2c63b280-fac6-11e8-8ede-1fa04599c7e5.png)

**Comment by Tom-ahawk** [comment]
I know your deCONZ instructions points to https://developers.home-assistant.io/docs/en/hassio_debugging.html , giving the instructions how to.

Not wanting to hijack your thread circuuz, I am quite worried to mess up my system, therefore asking this.

May I (running on RPI3/HassOS) also ask if it is possible to update the ConBee firmware, logging on to the RPI with “Open SSH” and then running the update commands?

**Comment by marthoc** [comment]
@circuuz - I haven't seen this before. This "protection mode" is a new feature that was added to HassOS but this is the first I've heard of it interacting with my upgrade script.

Can we just make sure you're following the steps outlined in the firmware upgrade readme, including logging into the host os via ssh?

**Comment by marthoc** [comment]
@Tom-ahawk I'm not sure I understand your question - in order to run the upgrade script you must be logged into the HassOS host via SSH, and the script will (should) upgrade both RaspBee and Conbee, though @circuuz may be pointing to an issue with that process.

**Comment by marthoc** [comment]
@circuuz Can you post the error that you are getting back on the command line when executing the command to invoke the firmware upgrade script?

**Comment by Tom-ahawk** [comment]
@marthoc 
Your instructions (Step1) points to “Use a USB drive formatted with FAT, ext4, or NTFS and name it CONFIG (case sensitive). Create an authorized_keys file containing your public key,…”

I am using the official add-on OpenSSH. Will your  firmware upgrade scrip work buy just logging into HassOS with OpenSSH, or does it only work  by following Step1 as described in the HA docs?

**Comment by marthoc** [comment]
@Tom-ahawk Using the sah addon will not work. You must follow the instructions.

**Comment by circuuz** [comment]
> @circuuz - I haven't seen this before. This "protection mode" is a new feature that was added to HassOS but this is the first I've heard of it interacting with my upgrade script.
> 
> Can we just make sure you're following the steps outlined in the firmware upgrade readme, including logging into the host os via ssh?

@marthoc I managed to solve it. The problem was that my SSH addon (https://github.com/hassio-addons/addon-ssh) had "Protection mode" enabled. When I disabled that, restarted the SSH addon, and then tried again it worked perfectly.
