### ISSUE TITLE
Upgrade Conbee firmware in Hassio

### ISSUE THREAD

**Issue by jansink** [marthoc/hassio-addons#46]
I connected to hassio with ssh on port 22222, but when I try to run the upgrade firmware script as described in the readme, then I get: "'docker' is not a hassio command." What am I missing? 
Also docker ps and logs are not working because of this.

**Comment by jansink** [comment]
Never mind, needed to 'login' first to go to the host system

**Comment by peterbartl** [comment]
I had the same problem a couple of minutes ago. Using Putty to connect to the host, I have to log in as "root". But then I also have to to type "login" (and press enter) before the docker command is available. As far as I can see, this extra "login" step is not described in the documentation or the linked documents. My suggestion would be to add this information in FIRMWARE-UPGRADE.md at Step 2.3
