### ISSUE TITLE
Sensors not showing in Phoscon, and old entity registration in log

### ISSUE THREAD

**Issue by Ralleberg** [marthoc/hassio-addons#47]
Hi,
Im struggling with my Conbee connected to my RP3 and Home Assistant.
The logs is indicating that my sensors have been registered og at least old nodes is still figuring in the system. My connected sensors page in the Phoscon app has no sensors included and the sensors can't be connected afterwards when trying to add new sensors.

My question is, how do I delete the "entity registry" for the Conbee to start from the beginning.

This is the log from one my sensors:

19:12:56:084 APS-DATA.indication from unknown node 0x00158D0002725BD5
19:12:56:115 ZCL attribute report 0x00158D00024A59F1 for cluster 0x0000, ep 0x01
19:12:56:115 0x00158D00024A59F1 extract Xiaomi special
19:12:56:115 	01 battery 2945 (0x0B81)
19:12:56:115 	03 temperature 28 °C
19:12:56:115 	04 unknown 5032 (0x13A8)
19:12:56:115 	05 RSSI dB (?) 20 (0x0014)
19:12:56:115 	06 LQI (?) 8590065664 (0x0200020000)
19:12:56:115 	08 unknown 516 (0x0204)
19:12:56:115 	0a unknown 0 (0x0000)
19:12:56:115 	64 on/off 0

**Comment by marthoc** [comment]
@Ralleberg I'm not sure this is an add-on specific problem. This sounds more like a deCONZ specific problem and I'd advise you to raise an issue on the Dresden Elektronik GitHub page.
