### ISSUE TITLE
Addon issues with Hassio on RPI 1 B+

### ISSUE THREAD

**Issue by UncleYstvan** [marthoc/hassio-addons#49]
Hi,

Thanks for the plugin!

I am struggling with the deconz addon on Hassio on my RPI 1B+.
I checked that this device is indeed compatible with the deconz USB stick, the add-on installed correctly but fails to start.

I use "/dev/ttyUSB0" as checked with `hassio hardware info`.

The only related line in the System logs is:
`INFO (SyncWorker_2) [hassio.docker.addon] Start Docker add-on marthoc/hassio-addon-deconz-armhf with version 2.05.52`
but the addon does not stay on and I failed to see where I can have more logs (no logs from the addon page)

I tested the stick on my computer, it works. 

My System:
- RPI 1 B+ with 2.4A power supply
- deconz usb stick
- HassOs version 1.13
- deCONZ 2.05.52

Any idea?

**Comment by uotcip** [comment]
My apologizes here is the exact entries in the System log after attempting to Start the Addon:

19-01-20 22:07:28 INFO (SyncWorker_0) [hassio.docker.interface] Clean marthoc/hassio-addon-deconz-armhf Docker application

19-01-20 22:07:33 INFO (SyncWorker_0) [hassio.docker.addon] Start Docker add-on marthoc/hassio-addon-deconz-armhf with version 2.05.55

**Comment by marthoc** [comment]
Are you setting the deconz device in the Hass.io addon options? The addon won't start if it is set to "null".
