### ISSUE TITLE
RaspBee and Bluetooth at the same time 

### ISSUE THREAD

**Issue by TheZoker** [marthoc/hassio-addons#50]
Hi there,

Am I able to use the RaspBee module and Bluetooth at the same time on a raspberry 3B+?

Thanks!

**Comment by puk1966** [comment]
Hi,

On my Raspberry 3b+ I use Raspbee and Bluetooth (home presence detection) together without problems. Bluetooth and Zigbee signals may interfere if you look on the forums, probably depending on hoe busy both modules are used.

**Comment by puk1966** [comment]
@marthoc : As you could see above, only way I could get Bluetooth and Raspbee working together is to use Raspbee on ttyS0 and Bluetooth on ttyAMA0. Is it wise/recommended to use the Raspbee on ttyS0 ? And is it possible to flash the Rasbpee over ttyS0 ?

**Comment by TheZoker** [comment]
So does bluetooth and raspbee work together now in your setup?

**Comment by TheZoker** [comment]
@puk1966 So does bluetooth and raspbee work together now in your setup?

**Comment by puk1966** [comment]
Yes it works in my setup

**Comment by puk1966** [comment]
@TheZoker : And did you try it?
