### ISSUE TITLE
Issue with newly added switches

### ISSUE THREAD

**Issue by Vout** [marthoc/hassio-addons#51]
Today i received 2 new Xiaomi Switches (WXKG02LM) and i have added them to my setup with the Phoscon app.

After adding them everything seems to work however after an reboot of HassIO it seems that Deconz isn't recognizing the switches anymore.

Working data output on the websocket port after adding the switch

`{"e":"changed","id":"10","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2019-01-08T18:58:36"},"t":"event","uniqueid":"00:15:8d:00:02:c9:37:86-01-0012"}
{"e":"changed","id":"10","r":"sensors","state":{"buttonevent":2002,"lastupdated":"2019-01-08T18:58:38"},"t":"event","uniqueid":"00:15:8d:00:02:c9:37:86-01-0012"}`

But after an reboot of Hassio / Deconz i don't see any data appearing on the websocket port anymore and i'm only getting the following messages inside the Deconz addon log

`20:24:19:103 APS-DATA.indication from unknown node 0x00158D0002C93786
20:24:19:103 no button map for: lumi.remote.b286acn01 ep: 0x01 cl: 0x0012 cmd: 0x0A pl[0]: 055
20:24:19:103 ZCL attribute report 0x00158D0002C93786 for cluster 0x0012, ep 0x01`

**Comment by maxandersen** [comment]
unrelated question - what do you use to get that "Working data output on the websocket port after adding the switch" ? wonder if something easy since I've not found it yet besides trying to setup appdemon to print events which is quite tedious.

**Comment by maxandersen** [comment]
never mind, realized it was easy to use `wsta` to get these dumped :)
