### ISSUE TITLE
default config is not a working config

### ISSUE THREAD

**Issue by maxandersen** [marthoc/hassio-addons#54]
Using https://github.com/neffs/hassio-addons/tree/master/deconz just works/starts out of the box.

Is there a reason why this addon *requires* one to setup the deconz_device option and not just set it to default: `/dev/ttyAMA0` so it will "just work" when starting ?

**Comment by sebstr1** [comment]
For me its `/dev/ttyUSB0`

**Comment by maxandersen** [comment]
if it matters my stick is conbee.

**Comment by nomadzx** [comment]
I actually have to use "/dev/ttyS0" for the Raspbee, as the others didn't work. I found that out when I tried using Dresden's image for Raspberry Pi I'm using a Pi 3b+.

**Comment by sebstr1** [comment]
> > For me its `/dev/ttyUSB0`
> 
> Yeah, that is what I tried too - no errors anywhere, only give away is that there are no lights identified ;/

To clarify; This is working very well for me so I have no issues with it. I also have the Conbee.

**Comment by maxandersen** [comment]
I tried what I could so far - for now I've forked the original repo and it works for me.

https://github.com/maxandersen/hassio-addons will always give you the latest-beta if you want to try it ;)

hopes someone have an idea how I can migrate over to the official one.
