### ISSUE TITLE
2.05.55.1 bugfix does not respect port settings

### ISSUE THREAD

**Issue by corvy** [marthoc/hassio-addons#64]
Hello, after last update the VNC server seems to work but still the web-port settings is not respected. 

Config:

> {
>   "deconz_device": "/dev/ttyAMA0",
>   "web_port": 8080,
>   "websockets_port": 8443,
>   "debug_info": 1,
>   "debug_aps": 0,
>   "debug_zcl": 0,
>   "debug_zdp": 0,
>   "debug_otau": 0,
>   "vnc": {
>     "active": true,
>     "port": 5900,
>     "password": "xxXXxx"
>   }
> }
> 

The GREAT news is that VNC works and I have successfully connected. Good work!

Log file:

> [Hass.io] Starting deCONZ Hass.io Addon...
> [Hass.io] Current deCONZ version: 2.05.55
> [Hass.io] Web UI port: 8080
> [Hass.io] Websockets port: 8443
> [Hass.io] deCONZ device: /dev/ttyAMA0
> [Hass.io] Starting VNC Server on Port 5900
> hostname: No address associated with hostname
> Cleaning stale pidfile '/data/.vnc/:0.pid'!
> New ':0 (root)' desktop at :0 on machine 
> Starting applications specified in /etc/X11/Xvnc-session
> Log file is /data/.vnc/:0.log
> Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /data/.vnc/passwd :0 to connect to the VNC server.
> libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
> libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
> libpng warning: iCCP: known incorrect sRGB profile
> 17:36:15:106 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
> 17:36:15:363 CTRL. 3.16.217:36:15:491 dev /dev/ttyAMA0
> 17:36:15:492 ZCLDB init file /data/.local/share/dresden-elektronik/deCONZ/zcldb.txt
> 17:36:15:681 parent process /bin/sh
> 17:36:15:682 gw run mode: docker/hassio
> 17:36:15:682 GW sd-card image version file does not exist: /data/.local/share/dresden-elektronik/deCONZ/gw-version
> 17:36:15:682 sd-card cid: 1b534d303030303010ffffffff00d36f
> 17:36:15:683 DB sqlite version 3.16.2
> 17:36:15:685 DB PRAGMA page_count: 42
> 17:36:15:685 DB PRAGMA page_size: 4096
> 17:36:15:685 DB PRAGMA freelist_count: 1
> 17:36:15:685 DB file size 172032 bytes, free pages 1
> 17:36:15:685 DB PRAGMA user_version: 6
> 17:36:15:685 DB cleanup
> 17:36:15:685 DB create temporary views
> 17:36:15:712 don't close database yet, keep open for 900 seconds
> 17:36:15:713 started websocket server at port 443
> 17:36:15:718 discovery updated announce interval to 10 minutes
> 17:36:15:722 found node plugin: libde_rest_plugin.so - REST API Plugin
> 17:36:15:726 found node plugin: libde_signal_plugin.so - Signal Monitor Plugin
> 17:36:15:745 found node plugin: libstd_otau_plugin.so - STD OTAU Plugin
> 17:36:15:784 dev /dev/ttyAMA0
> 17:36:16:011 discard sensor state push for 1: state/dark (already pushed)
> 17:36:16:012 discard sensor state push for 1: state/status (already pushed)
> 17:36:16:013 discard sensor state push for 1: state/lastupdated (already pushed)
> 17:36:16:512 dev /dev/ttyAMA0
> 17:36:16:549 dev /dev/ttyAMA0
> 17:36:16:920 Device firmware version 0x262F0500
> 17:36:16:953 unlocked max nodes: 200
> 17:36:17:149 Device protocol version: 0x0109
> 17:36:17:177 new node - ext: 0x00212effff02461a, nwk: 0x0000
> 17:36:17:642 SensorNode 3 set node 0x001788010211e98f
> 17:36:17:643 SensorNode 2 set node 0x001788010211e98f
> 17:36:17:644 SensorNode 4 set node 0x001788010211e98f
> 17:36:19:205 don't close database yet, keep open for 900 seconds
> 17:36:19:205 LightNode 7: Akvarie added
> 17:36:19:560 SensorNode 5 set node 0x0017880102c35cdd
> 17:36:27:370 don't close database yet, keep open for 900 seconds
> 17:36:27:371 LightNode 1: Sondres soverom added
> 17:36:27:668 don't close database yet, keep open for 900 seconds
> 17:36:27:669 LightNode 2: Bod Venstre added
> 17:36:28:070 don't close database yet, keep open for 900 seconds
> 17:36:28:070 LightNode 3: Bod Høyre added
> 17:36:28:429 don't close database yet, keep open for 900 seconds
> 17:36:28:430 LightNode 4: Inngangsdør Opp added
> 17:36:28:665 don't close database yet, keep open for 900 seconds
> 17:36:28:665 LightNode 5: Inngangsdør Ned added
> 17:36:29:321 SensorNode 8 set node 0x0017880104b547d2
> 17:36:29:321 SensorNode 6 set node 0x0017880104b547d2
> 17:36:29:322 SensorNode 7 set node 0x0017880104b547d2
> 17:36:29:688 don't close database yet, keep open for 900 seconds
> 17:36:29:689 LightNode 6: TV Stue added
> 17:36:30:186 SensorNode 11 set node 0x000b57fffe26f2cb
> 17:36:30:752 don't close database yet, keep open for 900 seconds
> 17:36:30:753 LightNode 8: Gang Oppe Sebastian added
> 17:36:31:222 don't close database yet, keep open for 900 seconds
> 17:36:31:223 LightNode 9: Gang Oppe Bad added
> 17:36:31:585 don't close database yet, keep open for 900 seconds
> 17:36:31:586 LightNode 10: Gang Oppe Trapp added
> 17:36:31:764 don't close database yet, keep open for 900 seconds
> 17:36:31:765 LightNode 11: Gang Oppe Toalett added
> 17:36:32:116 SensorNode 12 set node 0x000b57fffe89b4db
> 17:36:32:908 SensorNode 10 set node 0x0017880103c80687
> 17:36:33:097 don't close database yet, keep open for 900 seconds
> 17:36:33:098 LightNode 12: Stue Spot Gang added
> 17:36:33:716 don't close database yet, keep open for 900 seconds
> 17:36:33:717 LightNode 13: Stue Spot PC added
> 17:36:33:958 don't close database yet, keep open for 900 seconds
> 17:36:33:959 LightNode 14: Stue Spot Dør Vest added
> 17:36:34:386 don't close database yet, keep open for 900 seconds
> 17:36:34:387 LightNode 15: Stue Spot Peis added
> 17:36:34:806 don't close database yet, keep open for 900 seconds
> 17:36:34:806 LightNode 16: Stue Spot Dør Sør added

**Comment by jOOc** [comment]
I cant make a pull request but think its just wrong variables here. They are missing "HASSIO_" prefix
https://github.com/marthoc/docker-deconz/blob/master/amd64-hassio-addon/run.sh#L24-L25

After changing these it works for me

**Comment by pergolafabio** [comment]
Where did you change it? In config of hassio or in file itself?

**Comment by schisamo** [comment]
This should fix the issue in the underlying Docker containers: https://github.com/marthoc/docker-deconz/pull/93

**Comment by corvy** [comment]
I backed up config on deconz, uninstalled and reinstalled. All config was gone. VNC working, listen on port 80. All config done in hassio.

**Comment by forast3r** [comment]
Same behaviour here, if ports 80 or 443 are not used, deCONZ gets them, making other addons or programs like a reverse proxy unusable.

```
[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.55
[Hass.io] Web UI port: 8080
[Hass.io] Websockets port: 8443
[Hass.io] deCONZ device: /dev/ttyUSB0
[Hass.io] Starting VNC Server on Port 5900
hostname: Name or service not known
Cleaning stale pidfile '/data/.vnc/:0.pid'!

New ':0 (root)' desktop at :0 on machine 

Starting applications specified in /etc/X11/Xvnc-session
Log file is /data/.vnc/:0.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /data/.vnc/passwd :0 to connect to the VNC server.

libpng warning: iCCP: known incorrect sRGB profile
21:31:59:598 HTTP Server listen on address 0.0.0.0, port: 80, root: /usr/share/deCONZ/webapp/
```


On the other hand, if I first start manually my reverse proxy (that is using ports 80 and 443), when I run deCONZ, it works on the specified ports (8080, 8443):

```
[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.55
[Hass.io] Web UI port: 8080
[Hass.io] Websockets port: 8443
[Hass.io] deCONZ device: /dev/ttyUSB0
[Hass.io] Starting VNC Server on Port 5900
hostname: Name or service not known
Cleaning stale pidfile '/data/.vnc/:0.pid'!

New ':0 (root)' desktop at :0 on machine 

Starting applications specified in /etc/X11/Xvnc-session
Log file is /data/.vnc/:0.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /data/.vnc/passwd :0 to connect to the VNC server.

libpng warning: iCCP: known incorrect sRGB profile
21:41:00:708 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/
```

**Comment by corvy** [comment]
I think due to a bug it defaults to port 80 an 443. You need to vacate these ports until we get a fix merged.
