### ISSUE TITLE
Cannot open WebUI after upgrade to 2.05.55.1

### ISSUE THREAD

**Issue by bennydiamond** [marthoc/hassio-addons#65]
Freshly updated from 2.05.54.

WebUI is no longer available on default port.
Home Assistant no longer detects devices handled by deCONZ.

**Comment by eskimos2000** [comment]
Try to change to port 80 this is now known issue.

**Comment by lasse9000** [comment]
i can acces it witout the port number.
Before:
http://192.168.1.175:8181/pwa/
Now:
http://192.168.1.175/pwa/

**Comment by pather79** [comment]
I have the same issue, it can access it when I remove the port number, but I still don't know how to get the devices back to Hassio?

**Comment by corvy** [comment]
You need to delete the integration and set it up again. Then it works. When this is fixed you need to repeat.

**Comment by pather79** [comment]
Thank you for your answers, I now got it working again.

**Comment by Gronsak** [comment]
For people still waiting for a fix to this issue and don't want to redo the integration, if you have a snapshot you can roll back just the deconz addon to that version which should fix the issues caused by the port change
