### ISSUE TITLE
How do you put vnc active in configuration?

### ISSUE THREAD

**Issue by Klagio** [marthoc/hassio-addons#66]
Like below? Sorry newb here

{
  "deconz_device": "/dev/ttyUSB0",
  "web_port": 8080,
  "websockets_port": 8443,
  "debug_info": 1,
  "debug_aps": 0,
  "debug_zcl": 0,
  "debug_zdp": 0,
  "debug_otau": 0,
  "vnc active": true,
  "vnc port": 89,
  "vnc password": "sdfsdfsef"
}

**Comment by Klagio** [comment]
This also gives me error

{
  "deconz_device": "/dev/ttyUSB0",
  "web_port": 8080,
  "websockets_port": 8443,
  "debug_info": 1,
  "debug_aps": 0,
  "debug_zcl": 0,
  "debug_zdp": 0,
  "debug_otau": 0,
"vnc": {
"active": true,
"port": 5900,
"password": "xxXXxx"
}
}

**Comment by pergolafabio** [comment]
Have you updated to 55.1 release?

**Comment by pergolafabio** [comment]
my setup on 2.55.1 and working VNC

{
  "deconz_device": "/dev/ttyUSB0",
  "web_port": 80,
  "websockets_port": 8443,
  "debug_info": 1,
  "debug_aps": 0,
  "debug_zcl": 0,
  "debug_zdp": 0,
  "debug_otau": 0,
  "vnc": {
    "active": true,
    "port": 5900,
    "password": "changeme"
  }
}

**Comment by Klagio** [comment]
I have the Conbee on a pi3 (downloaded automatically latest beta from github) and HASSIO+Deconz addon (on a NUC, in the same LAN.
Now I am confused what I need to do

**Comment by corvy** [comment]
Deconz should be installed where you have the conbee. Hass does not need deconz unless the ZigBee device is local to the hass.io.

**Comment by Klagio** [comment]
DeCONZ is installed where I have the Conbee, but how does it link to HASSIO (on other host) if you don't install the addon?

**Comment by corvy** [comment]
Go into phoscon on the deconz install on port 80 or 8080 with a web browser. Enter config and go to gateway under settings menu. Click authorize to enable authorization. 

Go to Hass UI, click configuration, intergrations and click deconz to start intergration. 

Sorry if I do not remember exactly, but this is basically the process.

**Comment by cbho** [comment]
Deconz add-on v. 2.05.55.1
Hass.io v. 0.85.0
Running on an Intel NUC in Docker.
Config:
```
{
  "deconz_device": "/dev/ttyUSB0",
  "web_port": 8090,
  "websockets_port": 8444,
  "debug_info": 1,
  "debug_aps": 0,
  "debug_zcl": 0,
  "debug_zdp": 0,
  "debug_otau": 0,
  "vnc": {
    "active": true,
    "port": 5900,
    "password": "xxxxxxxx"
  }
}
```
Ports not the default ones, as this conflict with my UniFi Controller, but works fine.
However, trying to activate the VNC-feature results in the following:
```
[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.55
[Hass.io] Web UI port: 8090
[Hass.io] Websockets port: 8444
[Hass.io] deCONZ device: /dev/ttyUSB0
[Hass.io] Starting VNC Server on Port 5900
hostname: Name or service not known
tigervncserver: /usr/bin/Xtigervnc did not start up, please look into '/data/.vnc/:0.log' to determine the reason! -2
Invalid MIT-MAGIC-COOKIE-1 keyQXcbConnection: Could not connect to display :0
Aborted (core dumped)
```
Have not been able to find the "/data/.vnc/0.log"-file anywhere, unfortunately.

Wondering if it is the custom port that is the problem?

**Comment by corvy** [comment]
So deConz works but not VNC?

**Comment by cbho** [comment]
With the above config, with
```
  "vnc": {
    "active": true,
```
--> Nothing works - it crashes...

the same config, but 
```
  "vnc": {
    "active": false,
```
--> everything works fine (except of course the VNC ;-) )

**Comment by BertilJ** [comment]
I have to follow up with the same issue, Hass.io running 2.05.55.1. I can't get VNC to work either.

> [Hass.io] Starting deCONZ Hass.io Addon...
> [Hass.io] Current deCONZ version: 2.05.55
> [Hass.io] Web UI port: 8080
> [Hass.io] Websockets port: 8443
> [Hass.io] deCONZ device: /dev/ttyUSB0
> [Hass.io] Starting VNC Server on Port 5900
> hostname: No address associated with hostname
> Cleaning stale pidfile '/data/.vnc/:0.pid'!
> New ':0 (root)' desktop at :0 on machine 
> Starting applications specified in /etc/X11/Xvnc-session
> Log file is /data/.vnc/:0.log
> Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /data/.vnc/passwd :0 to connect to the VNC server.
> libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
> libEGL warning: DRI2: failed to open swrast (search paths /usr/lib/arm-linux-gnueabihf/dri:${ORIGIN}/dri:/usr/lib/dri)
> libpng warning: iCCP: known incorrect sRGB profile
> 21:48:08:989 HTTP Server listen on address 0.0.0.0, port: 8080, root: /usr/share/deCONZ/webapp/

Any ideas? Seems that several of us is having the same issue.

**Comment by pergolafabio** [comment]
no issues here with 55.1 and hassio addon , i have my webport configured to 80 instead of 8080 , but shouldnt normally not mather

**Comment by corvy** [comment]
Yes VNC works perfect. Needs a VNC client.
