### ISSUE TITLE
All gone after upgrade to 2.05.55.1

### ISSUE THREAD

**Issue by macce76** [marthoc/hassio-addons#67]
Hello.
After upgrade all my IKEA trådfri dissapered.
In phoscon app under gateway it says(firmware) not connected.
my config:
{
  "deconz_device": "/dev/ttyUSB1",
  "web_port": 8080,
  "websockets_port": 8443,
  "debug_info": 1,
  "debug_aps": 0,
  "debug_zcl": 0,
  "debug_zdp": 0,
  "debug_otau": 0,
  "vnc": {
    "active": false,
    "port": 5900,
    "password": "changeme"
  }
}

**Comment by forast3r** [comment]
Check your device name

**Comment by macce76** [comment]
Where do i check that....the config above worked until i updated it

**Comment by corvy** [comment]
Hass.io? You need to wait for fix or reintegration

**Comment by corvy** [comment]
Hass.io? You need to wait for fix or reintegration

https://github.com/marthoc/docker-deconz/pull/93

**Comment by macce76** [comment]
Ahhh ok, hope it will come soon 😉

**Comment by forast3r** [comment]
> Where do i check that....the config above worked until i updated it

in hass.io check the device in hass.io / system / hardware
