### ISSUE TITLE
Conbee is not found

### ISSUE THREAD

**Issue by alexvandervegt** [marthoc/hassio-addons#7]
The conbee is not found, i think because i have it in /dev/ttyUSB1 and not /dev/ttyUSB0

In a previous addon i used i could add something like this to the config.json:

  "devices": ["/dev/ttyUSB1:/dev/ttyAMA0:rwm"],

Maybe thats something you can work with?

**Comment by marthoc** [comment]
Yes that’s almost certainly the problem. There’s not much I can do about it from a user configuration point of view, but if you want to clone the repo, move the deconz directory to your Hassio addons directory, and make the modification to config.json, then you’ll be able to install your modified version from your Hassio local addon store. Let me know if it works!

**Comment by alexvandervegt** [comment]
Thanks, let me change it to:

"devices": ["/dev/ttyUSB1:rwm"],

**Comment by alexvandervegt** [comment]
Got some errors now, any clue?

18-05-01 07:32:35 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/local/deconz/config.json: does not match regular expression @ data['devices'][0]. Got '/dev/ttyUSB1:rwm'

**Comment by alexvandervegt** [comment]
@marthoc do you see something strange?

**Comment by alexvandervegt** [comment]
Got it working :D 

    "devices": ["/dev/ttyUSB1:/dev/ttyUSB0:rwm"],
