### ISSUE TITLE
This plugin does not support propagateSizeHints()

### ISSUE THREAD

**Issue by that1guy** [marthoc/hassio-addons#70]
Upgraded to `2.05.55.1` in Hass.io and I now receive the error: `This plugin does not support propagateSizeHints()`.  I have no idea where to go from here.

![image](https://user-images.githubusercontent.com/1218940/51434742-b8680e80-1c1c-11e9-8083-6bd92492bb13.png)

See this: https://github.com/dresden-elektronik/deconz-rest-plugin/issues/473

**Comment by corvy** [comment]
Are you sure you run 2.05.55.1? The error you get on VNC indicates that you run the 2.05.55 version....

**Comment by JasperKreeft** [comment]
Yes, I had the same problem. Updated to 2.05.55.1, but the log still indicates 2.05.55.
Can no longer find all devices and also not able to access the Phoscon web interface.

**Comment by corvy** [comment]
It's on port 80. Known issue. Not sure about the error above though..

**Comment by aluavin** [comment]
> Yes, I had the same problem. Updated to 2.05.55.1, but the log still indicates 2.05.55.
> Can no longer find all devices and also not able to access the Phoscon web interface.

i also don't see my lights after an update. is it possible to roll back somehow or did you fix the issue?

**Comment by marthoc** [comment]
New version is coming out shortly and should fix a bug in the start script.

As for "This plugin does not support propagateSizeHints()", that's an info message from the deCONZ software and can be safely ignored.

**Comment by that1guy** [comment]
I know this ticket is closed, but I just wanted to provide my solution juuuust in case.

1) In Hass.io you can revert back the snapshot if you have one (Click on Hass.io in the main nav -> click on Snapshots tab, then revert to your last snapshot (note: you can revert just deconz if you want and not the entire snapshot).

2) Reboot Hass.io, and notice that deconz is back up and running but it can't connect to any of your devices.

3) I had to reset all my Ikea lightbulbs (toggle the lightbulb on/off 6 times), then I had to scan for lightbulbs again and the bulb popped right back in with the previously configured name and grouping already there.  yay!

4) That's it, now that all the lightbulbs are recognized via deconz again, just reboot hass.io again and you're back online.

Thanks @marthoc.  I'll update again soon. :)
