### ISSUE TITLE
False Xiaomi buttonevent 1002

### ISSUE THREAD

**Issue by hkhaka** [marthoc/hassio-addons#72]
RPi3B+
Hass.io: 0.85.1
ConBee USB stick:
Version 2.05.57 / 2019-01-20
Firmware 262F0500

After upgrading to 2.05.57, strange things started to happen with my aquarium light. 
It randomly turned on and off. At night, when no one was home, aso...

I have it on a simple time automation, but I also have a Xiaomi button WXKG01LM just next to the aquarium, that has an event=1002 automation to toggle the light switch:
![image](https://user-images.githubusercontent.com/45568793/51633319-ae624a80-1f51-11e9-876d-79ec2ef9a4ee.png)

```
- id: aut_XButton1_Single
  alias: Knapp x1
  trigger:
  - event_data:
      event: 1002
      id: xswitch_2
    event_type: deconz_event
    platform: event
  action:
  - data:
      entity_id: switch.akvarium
    entity_id: switch.akvarium
    service: switch.toggle
```

After some debugging this evening, it seems like when the button reports its battery status, there is also a false 1002 event triggered.
I have three buttons that all generate the same false 1002 event repeatedly, about once every hour, when they report their battery/availability status.

This did not occur in the previous versions of the deCONZ plugin.

If I actually do press the button, physically, there is always a 1000 event (button down) first.
This I cannot see in the logs when the battery status is updated and the single, false 1002 event is sent.

**Battery status reported, triggering a false 1002 event:**
> 2019-01-23 17:57:59 DEBUG (MainThread) [pydeconz.deconzdevice] XSwitch_2: update battery with 100
> 2019-01-23 17:57:59 DEBUG (MainThread) [pydeconz.deconzdevice] XSwitch_2: update on with True
> 2019-01-23 17:57:59 DEBUG (MainThread) [pydeconz.deconzdevice] XSwitch_2: update reachable with True
> 2019-01-23 17:57:59 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"config":{"battery":100,"on":true,"reachable":true},"e":"changed","id":"9","r":"sensors","t":"event","uniqueid":"00:15:8d:00:02:0e:b3:f6-01-0006"}
> 2019-01-23 17:57:59 DEBUG (MainThread) [pydeconz.deconzdevice] XSwitch_2: update buttonevent with 1002
> 2019-01-23 17:57:59 DEBUG (MainThread) [pydeconz.deconzdevice] XSwitch_2: update lastupdated with 2019-01-23T16:57:59
> 2019-01-23 17:57:59 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event deconz_event[R]: id=xswitch_2, event=1002>
> 2019-01-23 17:57:59 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"e":"changed","id":"9","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2019-01-23T16:57:59"},"t":"event","uniqueid":"00:15:8d:00:02:0e:b3:f6-01-0006"}
> 2019-01-23 17:57:59 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event automation_triggered[L]: name=Knapp x1, entity_id=automation.knapp_x1>

**Physical press and release of button, triggering first a true 1000 event and then a true 1002 event, when button is released again:**
> 2019-01-23 21:03:34 DEBUG (MainThread) [pydeconz.deconzdevice] XSwitch_2: update buttonevent with 1000
> 2019-01-23 21:03:34 DEBUG (MainThread) [pydeconz.deconzdevice] XSwitch_2: update lastupdated with 2019-01-23T20:03:34
> 2019-01-23 21:03:34 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event deconz_event[R]: id=xswitch_2, event=1000>
> 2019-01-23 21:03:34 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"e":"changed","id":"9","r":"sensors","state":{"buttonevent":1000,"lastupdated":"2019-01-23T20:03:34"},"t":"event","uniqueid":"00:15:8d:00:02:0e:b3:f6-01-0006"}
> 2019-01-23 21:03:35 DEBUG (MainThread) [pydeconz.deconzdevice] XSwitch_2: update buttonevent with 1002
> 2019-01-23 21:03:35 DEBUG (MainThread) [pydeconz.deconzdevice] XSwitch_2: update lastupdated with 2019-01-23T20:03:35
> 2019-01-23 21:03:35 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event deconz_event[R]: id=xswitch_2, event=1002>
> 2019-01-23 21:03:35 DEBUG (MainThread) [pydeconz.websocket] Websocket data: {"e":"changed","id":"9","r":"sensors","state":{"buttonevent":1002,"lastupdated":"2019-01-23T20:03:35"},"t":"event","uniqueid":"00:15:8d:00:02:0e:b3:f6-01-0006"}
> 2019-01-23 21:03:35 DEBUG (MainThread) [homeassistant.core] Bus:Handling <Event automation_triggered[L]: name=Knapp x1, entity_id=automation.knapp_x1>

**Comment by marthoc** [comment]
This is a known issue with deCONZ (not this addon) and will be solved in the next release of the software.
