### ISSUE TITLE
Hassio 86.1 - Light Entities Not Recognised

### ISSUE THREAD

**Issue by nomadzx** [marthoc/hassio-addons#73]
Hi All,

I just upgraded to Hassio 86.1 and lost all my lights. They are no longer listed as entities. I can access Phoscon and control lights from there and they work. I have tried restarts, but still the problem recurs. Lovelace is now default for 86.1. I am using deconz version 2.05.54 as I am waiting to see of anyone is having problems with the latest version. For the moment I have reverted to an older snapshot, back to Hassio 85.1. Is anyone else having this problem with Hassio 86.1?

**Comment by corvy** [comment]
There was a note that device names will change in the new release. Could be related. I will upgrade this weekend and have a look at it.

**Comment by nomadzx** [comment]
Hi Corvy, It was not an issue of names changing, the entities from configuration disappeared. When I went to Configuration > Integrations > Configured > deCONZ Zigbee Gateway, only the default software daylight sensor was available. I am actually going to try upgrading to LoveLace on Hassio 85.1 and then try an upgrade to 86.2 to see if that does anything. I'll let you know when I get round to do it. Thanks.

**Comment by corvy** [comment]
Just upgraded and I get no issues on Lovelace. Works perfect.

**Comment by nomadzx** [comment]
Hi Corvy, I set up Lovelace before upgrading and by that time they had Hassio 86.3 issued. Everything is working on the deCONZ side now and everything is showing up. Lovelace is good, I like the ability to change on the fly without rebooting. Others should be aware though that automations may not work as they have a breaking change with the "time" parameter and waiting for a fix on the Hassio side for that.
Thanks
