### ISSUE TITLE
Xiaomi Window/Door sensors with temperatures?

### ISSUE THREAD

**Issue by maffee** [marthoc/hassio-addons#74]
Hi,

The deConz REST API apparently supports the temperature from different Xiaomi Aqara sensors, such as Window/Door sensor and Motion sensor (https://github.com/dresden-elektronik/deconz-rest-plugin/wiki/Supported-Devices). The temperature values are also shown in the Phoscon app.

If I have understood correctly, those values are not available at Home Assistant through the Add-on. Are there any plans to implement support for these?

I have a ton of different Aqara sensors and while I mostly have Aqara Multi sensors for temperature, it would still be a tremendous advantage to have the temperature values available from the other sensors too (I have 11 Window/Door sensors for example).

I am not a developer so unfortunately I am of no use in helping with this implementation part.

Thanks!

Best regards,
Markus

**Comment by marthoc** [comment]
This is related to the HASS component, not this addon specifically. Confusing I know. Paging @Kane610.

**Comment by Kane610** [comment]
Historically I've been reluctant to support these since they've been fairly inaccurate. But I'm making sure to cover all attributes of devices in pydeconz now which means that they will exist in there so I will shortly add support for the temperatures as an attribute on entities within a few weeks. Hass beta starts today so don't count on it before release 88

**Comment by maffee** [comment]
Sounds great, thank you! And damn, I was sure this was related to the addon itself, even tried to make sure of it =D Oh well.

**Comment by Kane610** [comment]
Marthoc is doing a great job, it is probably my fault when there are issues ;)

**Comment by maffee** [comment]
To clarify: I don't actually see this as an issue (even though I did open up an issue...). It doesn't have to support everything, especially because this is not a commercial product (the integration I mean).

Thank you both for the awesome work! I'll close this thread next.

**Comment by pergolafabio** [comment]
hi @Kane610  , is the temp value already present in HA? i dont see it yet in 89.2 ?

thnx in advance

**Comment by pergolafabio** [comment]
i see you added climate support, but thats not related, right?
