### ISSUE TITLE
access options.json - Deconz plugin

### ISSUE THREAD

**Issue by thomashup** [marthoc/hassio-addons#77]
Hi there,

I've installed the Deconz plugin in the Hassio menu, and got it to work :)

Now my question is, how do i access the opstions file, så i can activate VNC?

i tried to connect via ssh with user deconz, but did'nt succeed. 

What to do?

**Comment by corvy** [comment]
I think it is in the same folder that I created the OTAU in my post here: https://github.com/marthoc/hassio-addons/issues/30#issuecomment-459359637

If you add the marthoc build it is in the default. Another option is to just add it in the gui but you need to add it manually.

**Comment by corvy** [comment]
https://photos.app.goo.gl/UamgZLhKnQnu1Ngx9

This is my config. Not sure if it will work, but give it a go 😎 I would not change the web port from what you have or you will have to recreate the integration.

**Comment by thomashup** [comment]
Hi Corvy.

Sorry for my late answer.

I tried to edit it in the config in the Hassio gui, but it does not save my changes and it just goes back to this:

{
  "device": "/dev/ttyUSB0"
}

I'm a little affraid to do it by ssh and edit the config file directly, if i makes some mistakes.

Would it be a good idea, if it's possible, so add this setting to the gui, so for dummies like me it would be easier to activate this kind of settings?

**Comment by corvy** [comment]
I think the only option right now is to move to the marthoc version. This has what you seek 👌
