### ISSUE TITLE
deCONZ update to 2.05.25

### ISSUE THREAD

**Issue by alexvandervegt** [marthoc/hassio-addons#8]
Can you please update deconz to the latest version:

http://www.dresden-elektronik.de/rpi/deconz/beta/

Manup also changed the readme:

https://github.com/dresden-elektronik/deconz-rest-plugin

**Comment by marthoc** [comment]
Update is pushed. Closing.

**Comment by alexvandervegt** [comment]
Is there any way to automatic update the plugin?
