### ISSUE TITLE
WebUI

### ISSUE THREAD

**Issue by freenetwork** [marthoc/hassio-addons#81]
When click button open web UI. I can't get UI. Button cannot load port from setting

**Comment by froggy974** [comment]
same for me.
the webui port in the plugin interface link don't change in accordance with "web_port" custom value

**Comment by fantomnotabene** [comment]
Same here. 8080 forever. In config 9880, e.g.
On 9880 works perfectly, but not opening :9880 on "OPEN WEB UI"

**Comment by jjanderson** [comment]
Have you guys checked to see if your ports are open on the router? If you have a public domain for your home assistant (like duckdns) then you have to open the port on your router, otherwise, if connected locally, browse to your IP address of home assistant and then enter the port number....

**Comment by marthoc** [comment]
Yes this is just the way it is in Hass.io. Have to specify the webui port in config.json but it's not dynamic. Only other option is to disable the button altogether but I suspect most users don't change the webui port.

**Comment by fantomnotabene** [comment]
@marthoc But why is it working as expected when I change the port in the official Deconz addon?

**Comment by frenck** [comment]
@marthoc That is incorrect, it is dynamic. Could you re-open this issue? If you need assistance on implementing this, I can help you out.
