### ISSUE TITLE
Phoscon Group exhibits unsupported light options

### ISSUE THREAD

**Issue by capstan1** [marthoc/hassio-addons#85]
Hi,
I just ran into a smaller issue. I have 2 light groups (made in phoscon) which group dimmable only lights. I connected Phoscon to Hassio using this addon.

When turning on the group, HA frontend displays light options that aren't available for this lights (white saturation and color).
Option for individual light: 
![image](https://user-images.githubusercontent.com/17147867/54071908-9f222c80-4273-11e9-854b-9f36de379f1e.png)
options for 2 uqual lights grouped in phoscon:
![image](https://user-images.githubusercontent.com/17147867/54071915-beb95500-4273-11e9-8c11-79beccc1ab01.png)

I noticed this because my light alays is displayed as "blue" because thats the color home assistant assumes.

Can this be corrected?

**Comment by marthoc** [comment]
This isn’t an addon specific problem, and I’m not sure it’s a problem with the HA integration either - I think you should open an issue on the deconz repo, because what’s likely happening is that extraneous info is coming over the websocket for these groups.

**Comment by capstan1** [comment]
Okay, thanks! I checked what I see in the phoscon apps, so I thought the error happens here.

I'll post it there.

**Comment by capstan1** [comment]
Posted it [here](https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1341), in case you want to add anything!

Btw: thanks for your addon, it was so easy to set up!

**Comment by marthoc** [comment]
Just FYI - this addon has nothing to do with Phoscon - that is a part of deCONZ software. As far as I know this has been an issue for many deconz versions - light groups seem to have colour data when they aren't supposed to.

**Comment by capstan1** [comment]
Yeah, I know. 
I just have seen it's correct in phoscon and wrong in HA, so I've been suspecting the middleman.
