### ISSUE TITLE
Raspbee/RPI3b+ and wifi

### ISSUE THREAD

**Issue by JacHub** [marthoc/hassio-addons#86]
Hi Mark,

I have issues with Rasbpee and Raspberry Pi 3+. Cannot get Raspbee working.
My config:

Raspberry Pi 3+ / Powersupply 2.4A
RaspBee (configured on "/dev/ttyAMA0")
Latest Hassio (0.89.1 HassOS 2.10)
Changed config.txt with empty line at the end:
enable_uart=1
dtoverlay=pi3-miniuart-bt

If i start the pi with the raspbee and an network cable the every thing is working well.
But when i start the pr without the cable it normally connects with wifi but with the raspbee mounted
it cant connect to the router. After removing the raspbee it is working again and it connects to the router again.

Do you have an idee?

**Comment by puk1966** [comment]
Try to switch your Raspberrypi Wifi from 2.4 GHz to 5 Ghz.

Zigbee and Wifi are in the same 2.4 GHz frequency range and Raspbee and Wifi are very close to each other on the Raspberrypi board, check this link:

https://support.metageek.com/hc/en-us/articles/203845040-ZigBee-and-WiFi-Coexistence
