### ISSUE TITLE
All devices greyed out after raspberry pi reboot

### ISSUE THREAD

**Issue by danielsjf** [marthoc/hassio-addons#88]
I'm using hassio on a raspberry pi 3 B+ in combination with this add-on and a conbee stick. Each time after a reboot (in practice when I update hassos), I lose my full zigbee network. Actually, the phoscon app still shows them but greyed out.

I have to manually reconnect all devices in order to get them back. Deconz still recognises them as the old devices though. There is no need to remove the old greyed out devices once they are reconnected. Reconnecting involves basically resetting the devices.

I'm on the latest addon version and my stick has the latest firmware. It just hapenned again after moving from hassos 2.8 to 2.10.

**Comment by alie2n** [comment]
I am also experiencing this issue. I just setup a new hass.io environment and moved to marthdoc deconz due to a bug in the official addon. 
Everytime I reboot the hass.io system the whole deconz zigbee is deconnected.... :(
