### ISSUE TITLE
how to update firmware ? firmware failed

### ISSUE THREAD

**Issue by pergolafabio** [marthoc/hassio-addons#89]
i , am running hassio

in phoscon app, i see new firmware
when i click on it, it doesnt update
running deconz version : 2.05.60

thiis is errorlog : 

21:42:38:664 GW firmware start update (device not connected)
21:42:38:904 GW firmware update exit code 255
21:42:39:638 Wait reconnect after firmware update

offcourse it was 'connected' 

see here screenshot : 
https://www.dropbox.com/s/5xvtnp0ph9p7e73/deconz1.JPG?dl=0

what could be wrong?

**Comment by marthoc** [comment]
Please see the instructions here: https://github.com/marthoc/hassio-addons/blob/master/deconz/FIRMWARE-UPGRADE.md.

**Comment by pergolafabio** [comment]
That was the old way? But I thought it was now possible with phoscon?
