### ISSUE TITLE
Can you update deconz again?

### ISSUE THREAD

**Issue by alexvandervegt** [marthoc/hassio-addons#9]
Can you please bump deconz to the latest version?

**Comment by alexvandervegt** [comment]
@marthoc ??

**Comment by marthoc** [comment]
You’ll need to bug @manup of DE... my repo has been updated but since there is no 2.05.26 deb for Ubuntu/x64 posted, the build is failing.

**Comment by alexvandervegt** [comment]
You can find them here:

http://www.dresden-elektronik.de/rpi/deconz/beta/

Also they are already on 2.05.27 :)

**Comment by manup** [comment]
Version 2.05.28 comes later today for all platforms, sorry for the delay :)

**Comment by alexvandervegt** [comment]
awesome!

**Comment by alexvandervegt** [comment]
@marthoc its updated, can you please also update?
