### ISSUE TITLE
Conbee II /dev/ttyACM0

### ISSUE THREAD

**Issue by plantoschka** [marthoc/hassio-addons#92]
I've received my Conbee II yesterday and tried it out on my Intel NUC running Ubuntu 18.04 with HASS.IO in Docker.

My device is attached to /dev/ttyACM0 instead of /dev/ttyUSB0 is that normal? Also seems to me when I plug in the stick it disables Bluetooth my Intel NUC.
When I try to run the firmware upgrade it tells me that it cannot detect any FTDI devices.

Everything seems work fine besides that. Just some Xiaomi Sensors get lost after a couple of hours.
But I think this will be fixed in the 2.05.62 release (https://github.com/dresden-elektronik/deconz-rest-plugin/issues/1074). Hope this addon will be updated soon.

**Comment by KayGt3** [comment]
Same issue for me as @plantoschka

**Comment by Haansen** [comment]
Everything works in phoscon but in firmware  udate same issue . Tried both local and docker same issue .

**Comment by KayGt3** [comment]
Nice to hear that we are not alone. Other things, I have Philips and Ikea motion sensor and they works well, but Xiaomi door sensor became unreachabale after 2/3 hours.

**Comment by bdb12** [comment]
I ungraded from Conbee 1 to 2 and can see stuff in Phoscon but cannot control anything. Have changed the path to /dev/ttyACM0 instead of /dev/ttyUSB0.

**Comment by plantoschka** [comment]
Problem is fixed with newer Conbee II firmware and 2.05.62.
/dev/ttyACM0 seems to be normal.

**Comment by hellcry37** [comment]
I am on 2.05.71 and still have bluetooth issues on my intel nuc, deconz conbee ii works ok but bluetooth tracker on home assistant not so much, same issue deconz conbee ii connected on /dev/ttyACM0

**Comment by hellcry37** [comment]
I can confirm this was an issue i turned off onboard bluetooth and installed a dongle, bluetooth tracker works OK now so is definitively a problem /dev/ttyACM0 interfering with onboard bluetooth
