### ISSUE TITLE
Addon does not seem to start

### ISSUE THREAD

**Issue by esseki** [marthoc/hassio-addons#96]
Hi,

thank you for your work maintaining this addon. I'm a big fan of the Deconz/Conbee solution that i'm running for a while on its own dedicated RPi. I would really appreciate having a chance migrating and using it as an Hassio Addon.

The problem :
- the addon seem to be running (i have a green dot close to the "2.05.63" version number and the buttons "restart" and "stop" available)
- but i can not reach the Phoscon webapp when clicking on the "Open Web Ui" button.
- URL seems to be fine "http://192.168.100.14:8080/" considering that "192.168.100.14" is the IP of my HA server box but i'm getting a "This webpage is not available ERR_CONNECTION_REFUSED" error in Chrome.

Deconz addon Logs:
```
[Hass.io] Starting deCONZ Hass.io Addon...
[Hass.io] Current deCONZ version: 2.05.63
[Hass.io] Web UI port: 8080
[Hass.io] Websockets port: 8443
[Hass.io] deCONZ device: /dev/ttyUSB0
[Hass.io] Starting in minimal mode, without VNC GUI
libpng warning: iCCP: known incorrect sRGB profile
Illegal instruction (core dumped)
```
I assume the last line in the log "**Illegal instruction (core dumped)**" is the reason for my problem. But i can't find a way to get more info/log about the possible reason for this error whatever the debug i add in the addon config. 

Deconz addon config:
```
{
  "deconz_device": "/dev/ttyUSB0",
  "web_port": 8080,
  "websockets_port": 8443,
  "debug_info": 1,
  "debug_aps": 1,
  "debug_zcl": 1,
  "debug_zdp": 1,
  "debug_otau": 1,
  "vnc": {
    "active": false,
    "port": 5900,
    "password": "########"
  }
}
```
HASS.IO logs
```
19-04-23 11:26:41 INFO (MainThread) [hassio.updater] Fetch update data from https://s3.amazonaws.com/hassio-version/stable.json
19-04-23 11:26:41 INFO (MainThread) [hassio.addons.git] Update add-on https://github.com/marthoc/hassio-addons repository
19-04-23 11:26:41 INFO (MainThread) [hassio.addons.git] Update add-on https://github.com/home-assistant/hassio-addons repository
19-04-23 11:26:42 INFO (MainThread) [hassio.addons.git] Update add-on https://github.com/hassio-addons/repository repository
19-04-23 11:26:43 WARNING (MainThread) [hassio.addons.data] Can't read /data/addons/git/69bb46cb/dnsomatic/config.json: required key not provided @ data['arch']. Got None
19-04-23 11:26:43 INFO (MainThread) [hassio.addons] Load add-ons: 59 all - 0 new - 0 remove
19-04-23 11:37:29 INFO (SyncWorker_4) [hassio.docker.interface] Clean addon_69bb46cb_deconz application
19-04-23 11:37:30 INFO (SyncWorker_4) [hassio.docker.addon] Start Docker add-on marthoc/hassio-addon-deconz-aarch64 with version 2.05.63
```

To give you some details about my config, i'm running:
- HASSOS 2.11
- from an Odroid C2 (aarch64)
- your Deconz addon version 2.05.63 (that is supposed to be compatible with aarch64 according to https://github.com/marthoc/hassio-addons/issues/15)
- with a Conbee 1

**Comment by marthoc** [comment]
I'm suspecting that this is related to the 64-bit OS. This add-on is only experimentally compatible with 64-bit systems. It just spoofs the manifest to allow the armhf version to get pulled on aarch64 or arm64 versions. Unfortunately I don't have either an Odroid C2 or Raspi 3B+ to test on so I can't offer better support. Now if someone was willing to donate some hardware...

**Comment by manutoky** [comment]
Is there any progress on this issue? Maybe someone found a workaround? I just started using Conbee2 on a Odroid C2 running hass.io inside a docker environment on armbian (at least I tried). I get the same "illegal instruction" error when trying to start the addon.
